use crate::app::prelude::*;

pub(crate) fn check_render_movement_contracts(root: &Path, findings: &mut Vec<Finding>) {
    require_contains(
        root,
        findings,
        "ARCH-RENDER-MOVEMENT",
        "src/render/animation_introspection.rs",
        &[
            "rendered_movement",
            "rendered_movement_delta_px",
            "rendered_node_coverage_frozen",
            "report_fails_when_selected_rendered_coverage_is_frozen",
        ],
    );
    require_contains(
        root,
        findings,
        "ARCH-RENDER-MOVEMENT",
        "src/bin/scena/verify_animation/observations.rs",
        &[
            "node_rendered_coverage",
            "rendered_centroid_css_px",
            "selected_observed_node",
            "changed_node_coverage",
        ],
    );
    require_contains(
        root,
        findings,
        "ARCH-RENDER-MOVEMENT",
        "src/bin/scena/verify_animation/rendered_coverage.rs",
        &[
            "RenderedNodeCoverage",
            "rendered_node_coverages",
            "project_aabb_from_capture",
            "screen_region_from_rect",
        ],
    );
    require_contains(
        root,
        findings,
        "ARCH-RENDER-MOVEMENT",
        "tests/scena_cli_agent.rs",
        &[
            "rendered_movement",
            "rendered_movement_delta_px",
            "rendered_centroid_css_px",
        ],
    );
    require_contains(
        root,
        findings,
        "ARCH-RENDER-MOVEMENT",
        "src/render/movement_tests.rs",
        &[
            "transform_only_gpu_prepare_updates_draw_uniforms_without_recollecting_primitives",
            "transform_only_cpu_prepare_moves_rendered_mesh_pixels",
            "line_geometry_gpu_prepare_updates_draw_uniforms_without_recollecting_strokes",
            "must move the rendered mesh pixels",
        ],
    );
    require_contains(
        root,
        findings,
        "ARCH-RENDER-MOVEMENT",
        "src/render/tests.rs",
        &[
            "visibility_middle_primitive_reencodes_batches_without_vertex_reupload",
            "visible_pixels.saturating_sub(hidden_pixels)",
            "must remove the hidden primitive from rendered pixels",
        ],
    );
    require_contains(
        root,
        findings,
        "ARCH-RENDER-MOVEMENT",
        "src/render/phase5_tests.rs",
        &[
            "transform_animation_gpu_prepare_uses_dynamic_path_without_recollecting_primitives",
            "imported_gltf_transform_gpu_prepare_moves_rendered_pixels_via_dynamic_path",
            "must move rendered mesh pixels",
        ],
    );
    require_contains(
        root,
        findings,
        "ARCH-RENDER-MOVEMENT",
        "tests/support/parity.rs",
        &[
            "pub enum RenderBackend",
            "require_cpu_gpu_parity_adapter_or_skip",
            "configure_lavapipe_adapter",
            "render_scene_cpu_gpu_pair",
            "pub struct ParitySweep",
            "sobel_luminance_energy_in_region",
        ],
    );
    require_contains(
        root,
        findings,
        "ARCH-RENDER-MOVEMENT",
        "tests/dynamic_transform_parity.rs",
        &[
            "scena.dynamic_transform_parity_sweep.v1",
            "dynamic_transform_motion_matches_cpu_and_gpu_for_authored_animation_and_imports",
            "require_cpu_gpu_parity_adapter_or_skip",
            "renderer_for_backend",
            "authored-set-transform",
            "authored-animation-seek",
            "imported-gltf-set-transform",
            "GPU path must move rendered object pixels",
        ],
    );
    require_contains(
        root,
        findings,
        "ARCH-RENDER-MOVEMENT",
        "scripts/probe_showcase_demo.mjs",
        &[
            "assertConnectorReplayMovesCanvas",
            "connector replay changed DOM state without moving the rendered WebGL part",
            "connector_replay_canvas_movement",
            "sampledCanvasPixels",
            "canvasDiffStats",
            "SCENA_SHOWCASE_CONNECTOR_ONLY",
            "connector-only",
        ],
    );
}
