use crate::app::prelude::*;

pub(crate) fn check_render_quality_contracts(root: &Path, findings: &mut Vec<Finding>) {
    require_contains(
        root,
        findings,
        "ARCH-RENDER-QUALITY",
        "src/render/quality.rs",
        &[
            "RENDER_QUALITY_SCHEMA_V1",
            "label_ink_isolation",
            "label_missing_antialiasing",
            "label_background_not_uniform",
            "label_background_color_mismatch",
            "severe_black_crush",
            "severe_blown_out",
            "blank_frame",
            "subject_tiny_in_frame",
            "low_clip_fraction_too_high",
            "high_clip_fraction_too_high",
            "contrast_too_flat",
            "edge_energy_too_low",
            "noise_outlier_fraction_too_high",
            "reference_quality_metrics",
            "ssim_grayscale",
            "line_missing_antialiasing",
            "line_not_straight",
        ],
    );
    require_contains(
        root,
        findings,
        "ARCH-RENDER-QUALITY",
        "src/render/quality/tests/label.rs",
        &[
            "label_quality_known_bad_fails_exact_reason_and_good_passes",
            "label_quality_known_bad_gpu_eroded_fixture_fails_exact_reason",
            "label-known-bad-eroded.ppm",
            "label-known-bad-gpu-eroded.ppm",
            "label-known-good-antialiased.ppm",
            "label_quality_known_bad_bitmap_fixture_fails_antialiasing_reason",
            "label-known-bad-bitmap.ppm",
            "label_background_quality_known_bad_fails_exact_reason_and_good_passes",
            "label_background_not_uniform",
        ],
    );
    require_contains(
        root,
        findings,
        "ARCH-RENDER-QUALITY",
        "src/render/quality/tests/frame_reference.rs",
        &[
            "baseline_quality_fixtures_cover_blank_blown_out_and_tiny_codes",
            "opt_in_quality_fixtures_cover_exposure_contrast_and_noise_codes",
            "reference_quality_fixtures_cover_abs_delta_e_and_ssim_metrics",
            "grayscale_ssim_matches_reference_anchors",
            "severe_black_crush",
            "severe_blown_out",
            "blank_frame",
            "subject_tiny_in_frame",
            "low_clip_fraction_too_high",
            "high_clip_fraction_too_high",
            "contrast_too_flat",
            "edge_energy_too_low",
            "noise_outlier_fraction_too_high",
        ],
    );
    require_contains(
        root,
        findings,
        "ARCH-RENDER-QUALITY",
        "src/render/quality/tests/line_geometry.rs",
        &[
            "line_quality_known_bad_fails_exact_reason_and_good_passes",
            "line-known-bad-aliased.ppm",
            "line-known-good-antialiased.ppm",
            "line_missing_antialiasing",
            "geometry_edge_quality_known_bad_fails_exact_reason_and_good_passes",
            "geometry_missing_antialiasing",
        ],
    );
    require_contains(
        root,
        findings,
        "ARCH-RENDER-QUALITY",
        "src/render/quality/geometry.rs",
        &["geometry_edge_metrics", "geometry_missing_antialiasing"],
    );
    require_contains(
        root,
        findings,
        "ARCH-RENDER-QUALITY",
        "src/render/quality/area_light.rs",
        &[
            "area_light_shadow_metrics",
            "area_light_soft_shadow_checked",
            "area_light_soft_shadow_insufficient",
        ],
    );
    require_contains(
        root,
        findings,
        "ARCH-RENDER-QUALITY",
        "src/render/quality/grounding.rs",
        &[
            "contact_shadow_metrics",
            "evaluate_grounding_region_quality",
            "contact_shadow_checked",
            "contact_shadow_missing",
        ],
    );
    require_contains(
        root,
        findings,
        "ARCH-RENDER-QUALITY",
        "src/render/quality/depth_of_field.rs",
        &[
            "depth_of_field_metrics",
            "evaluate_depth_of_field_region_quality",
            "depth_of_field_checked",
            "depth_of_field_background_detail_missing",
            "depth_of_field_blur_insufficient",
            "depth_of_field_focal_softened",
        ],
    );
    require_contains(
        root,
        findings,
        "ARCH-RENDER-QUALITY",
        "src/render/output/depth_of_field.rs",
        &[
            "DepthOfFieldConfig",
            "apply_depth_of_field_rgba8",
            "dof_radius_px",
        ],
    );
    require_contains(
        root,
        findings,
        "ARCH-RENDER-QUALITY",
        "src/render/gpu/post/dof.rs",
        &[
            "scena.gpu_post.depth_of_field_pipeline",
            "scena.gpu_post.depth_of_field_pass",
        ],
    );
    require_contains(
        root,
        findings,
        "ARCH-RENDER-QUALITY",
        "src/render/gpu/post/mod.rs",
        &["depth_bind_group(resources, current)"],
    );
    require_contains(
        root,
        findings,
        "ARCH-RENDER-QUALITY",
        "src/render/gpu/post/resources.rs",
        &[
            "scena.gpu_post.scene_depth_bind_group",
            "scena.gpu_post.ping_depth_bind_group",
            "scena.gpu_post.pong_depth_bind_group",
        ],
    );
    require_contains(
        root,
        findings,
        "ARCH-RENDER-QUALITY",
        "src/render/gpu/post/dof.wgsl",
        &[
            "sample_scene_depth",
            "dof_radius",
            "let focus_distance = max(post.config.x, 0.001)",
            "let image_focus = focal_m * focus_distance",
            "let coc_m = aperture_diameter * abs(image_depth - image_focus)",
            "textureLoad(source_texture",
        ],
    );
    require_contains(
        root,
        findings,
        "ARCH-RENDER-QUALITY",
        "src/diagnostics/post_processing.rs",
        &["depth_of_field", "dof_depth_source", "DepthOfField"],
    );
    require_contains(
        root,
        findings,
        "ARCH-RENDER-QUALITY",
        "tests/label_text.rs",
        &[
            "label_text_truetype_preserves_antialiasing_coverage_on_cpu",
            "label_text_truetype_preserves_antialiasing_coverage_on_headless_gpu",
            "label_text_truetype_atlas_matches_cpu_and_headless_gpu_with_tolerance",
            "truetype_aa_label_region",
            "frame_delta_in_bounds",
            "full label region",
            "intermediate_gray_pixel_count",
            "truetype-label-aa-cpu",
            "truetype-label-aa-gpu",
            "truetype-label-atlas-parity-cpu-crop",
            "truetype-label-atlas-parity-gpu-crop",
        ],
    );
    require_contains(
        root,
        findings,
        "ARCH-RENDER-QUALITY",
        "src/bin/scena/recipe/quality/depth_of_field.rs",
        &[
            "append_depth_of_field_checks",
            "render_depth_of_field_source_capture",
            "depth_of_field_not_enabled",
            "depth_of_field_baseline_backend_mismatch",
            "depth_of_field_baseline_size_mismatch",
        ],
    );
    require_contains(
        root,
        findings,
        "ARCH-RENDER-QUALITY",
        "tests/scena_cli_recipe.rs",
        &[
            "scena_recipe_render_verify_reports_reference_quality_failure",
            "reference_ssim_too_low",
            "wrong-reference-ssim",
            "scena_recipe_render_verify_passes_quality_per_line_region_on_cpu_and_gpu",
            "expect_quality.line.segment",
            "scena_recipe_render_verify_fails_geometry_edge_quality_without_sample_aa_on_cpu_and_gpu",
            "scena_recipe_render_verify_passes_geometry_edge_quality_with_msaa4_on_gpu",
            "scena_recipe_render_area_light_broadens_specular_highlight_on_cpu_and_gpu",
            "specular-spread-cpu-metrics.json",
            "specular-spread-gpu-metrics.json",
            "scena.specular_spread_probe.v1",
            "scena_recipe_render_area_light_ltc_specular_matches_cpu_and_gpu",
            "area-light-ltc-cpu-gpu-parity-{case}.json",
            "scena.area_light_ltc_parity_probe.v1",
            "rect-low-roughness",
            "disc-mid-roughness",
            "sphere-high-roughness",
            "scena_recipe_render_area_light_caster_darkens_tessellated_receiver_on_cpu_and_gpu",
            "area-shadow-{backend}-metrics.json",
            "scena.area_shadow_probe.v1",
            "scena_recipe_render_verify_checks_area_light_soft_shadow_on_cpu_and_gpu",
            "scena_recipe_render_verify_checks_area_light_soft_shadow_for_all_shapes_on_cpu_and_gpu",
            "expect_quality.area_light.target",
            "area_light_soft_shadow_checked",
            "area_light_soft_shadow_insufficient",
            "scena_recipe_render_verify_checks_contact_shadow_grounding_on_cpu_and_gpu",
            "expect_quality.grounding.target",
            "contact_shadow_checked",
            "contact_shadow_missing",
            "scena_recipe_render_verify_checks_depth_of_field_on_cpu_and_gpu",
            "expect_quality.depth_of_field",
            "depth_of_field_not_enabled",
            "depth_of_field_blur_insufficient",
            "depth_of_field_checked",
            "scena_recipe_render_supersample_changes_curve_grid_and_specular_pixels_on_cpu_and_gpu",
            "scena_recipe_render_gpu_reconstruction_widens_dashboard_bar_and_preserves_grid_edges_without_haloing",
            "scena_recipe_render_culls_offscreen_node_without_culling_visible_node_on_cpu_and_gpu",
            "dashboard-bar-reconstruction-metrics.json",
            "dashboard-grid-reconstruction-metrics.json",
            "grid-floor-line-detail-quality.json",
            "scena_recipe_render_gpu_msaa_grid_floor_is_occluded_by_object",
            "red_grid_pixels_inside_object_interior",
            "nodes_summary\"][\"culled\"]",
            "scena_recipe_render_verify_emits_composition_report_for_declared_nodes",
            "scena_recipe_render_verify_fails_required_composition_coverage_when_node_is_offscreen",
            "scena_recipe_render_verify_checks_callout_annotation_ownership",
            "scena_recipe_render_verify_checks_grid_floor_ownership",
            "scena_recipe_render_verify_checks_measurement_overlay_ownership",
            "scena_recipe_render_verify_fails_overlay_line_through_label",
            "scena_recipe_render_verify_fails_floating_grounded_node_on_cpu_and_gpu",
            "scena_recipe_render_verify_checks_helper_layer_occlusion_on_cpu_and_gpu",
            "scena_recipe_render_verify_checks_object_depth_order_on_cpu_and_gpu",
            "scena_recipe_render_verify_rejects_ambiguous_object_depth_colors_on_cpu_and_gpu",
            "scena_recipe_render_verify_checks_object_framing_on_cpu_and_gpu",
            "scena_recipe_render_verify_checks_backend_conformance_on_cpu_and_gpu",
            "scena_recipe_render_verify_checks_clipping_and_section_conformance_on_cpu_and_gpu",
            "scena_recipe_render_verify_checks_material_variant_state_on_cpu_and_gpu",
            "scena_recipe_render_verify_checks_object_exposure_and_salience_on_cpu_and_gpu",
            "scena_recipe_render_verify_checks_texture_material_result_on_cpu_and_gpu",
            "visible_pixel_coverage_available",
            "visible_pixel_coverage_missing",
            "material_base_color_available",
            "subject_fit_sane",
            "subject_too_small_in_frame",
            "subject_exposure_sane",
            "subject_black_crushed",
            "subject_blown_out",
            "subject_salience_too_low",
            "texture_result_visible",
            "texture_result_flat",
            "callout_target_attached",
            "callout_overlay_output_projected",
            "grid_floor_output_owned",
            "measurement_overlay_output_projected",
            "overlay_label_intersects_line",
            "overlay_label_clear_of_lines",
            "ground_contact_present",
            "ground_contact_missing",
            "expect_helper_occluded",
            "helper_layer_occluded_by_subject",
            "helper_layer_overdraws_subject",
            "expect_occlusion",
            "object_depth_order_satisfied",
            "object_depth_order_mismatch",
            "object_depth_order_color_ambiguous",
            "expect_backend",
            "backend_expectation_satisfied",
            "backend_expectation_mismatch",
            "expect_clipping",
            "clipping_plane_count_satisfied",
            "clipping_plane_count_mismatch",
            "section_box_active",
            "section_box_missing",
            "section_box_inversion_satisfied",
            "section_box_inversion_mismatch",
            "expect_state",
            "material_variant_state_satisfied",
            "material_variant_state_mismatch",
            "render_antialiasing_active",
            "render_supersample_active",
            "render_reconstruction_active",
            "\"schema\": \"scena.scene_recipe.v1\"",
            "declared_node_not_drawn",
            "source\"] == \"composition\"",
            "\"supersample\": supersample",
        ],
    );
    require_contains(
        root,
        findings,
        "ARCH-RENDER-QUALITY",
        "tests/scene_recipe_contracts.rs",
        &[
            "scene_recipe_depth_of_field_quality_threshold_domains_match_metrics",
            "Sobel-energy DoF thresholds are measured non-negative values",
            "$.expect.expect_quality.depth_of_field.min_background_sobel_drop_fraction",
        ],
    );
    require_contains(
        root,
        findings,
        "ARCH-RENDER-QUALITY",
        "src/render/cpu_resolve.rs",
        &[
            "downsample_rgba8_reconstruction_filter",
            "rgba8_supersample_downsample_averages_rgb_in_linear_light",
            "srgb8_to_linear",
            "ReconstructionFilter::Gaussian",
        ],
    );
    require_contains(
        root,
        findings,
        "ARCH-RENDER-QUALITY",
        "src/render/gpu/post/mod.rs",
        &[
            "settings.reflections",
            "ssr::encode",
            "counts.screen_space_reflections",
        ],
    );
    require_contains(
        root,
        findings,
        "ARCH-RENDER-QUALITY",
        "src/render/gpu/post/ssr.wgsl",
        &[
            "horizon_y",
            "reflected_sample",
            "mix(source.rgb, reflected, alpha)",
        ],
    );
    require_contains(
        root,
        findings,
        "ARCH-RENDER-QUALITY",
        "tests/assets/stable-contracts/render_quality.v1.json",
        &[
            "\"schema\": \"scena.render_quality.v1\"",
            "\"code\": \"label_ink_isolation\"",
            "\"code\": \"line_missing_antialiasing\"",
            "\"code\": \"geometry_missing_antialiasing\"",
            "\"code\": \"reflection_structure_missing\"",
            "\"code\": \"reflection_chrome_read_missing\"",
            "\"code\": \"contact_shadow_missing\"",
            "\"code\": \"depth_of_field_checked\"",
            "\"fix_hint\"",
        ],
    );
    require_contains(
        root,
        findings,
        "ARCH-RENDER-QUALITY",
        "docs/schema-contracts.md",
        &[
            "### `scena.render_quality.v1`",
            "`label_ink_isolation`",
            "`label_missing_antialiasing`",
            "`line_missing_antialiasing`",
            "`geometry_missing_antialiasing`",
            "`reflection_structure_missing`",
            "`reflection_chrome_read_missing`",
            "`contact_shadow_missing`",
            "`depth_of_field_checked`",
            "`reference_ssim_too_low`",
        ],
    );
    super::quality_composition::check_scene_composition_quality_contracts(root, findings);
    check_label_atlas_replaced_cell_primitives(root, findings);
}

fn check_label_atlas_replaced_cell_primitives(root: &Path, findings: &mut Vec<Finding>) {
    require_contains(
        root,
        findings,
        "ARCH-LABEL-ATLAS",
        "src/render/prepare/labels.rs",
        &[
            "prepare_label_atlas",
            "PreparedLabelAtlas",
            "PreparedLabelQuad",
        ],
    );
    require_contains(
        root,
        findings,
        "ARCH-LABEL-ATLAS",
        "src/render/gpu/labels.rs",
        &[
            "manual_bilinear_coverage",
            "scena.gpu_labels.atlas_texture",
            "scena.gpu_labels.pipeline",
        ],
    );
    require_contains(
        root,
        findings,
        "ARCH-LABEL-ATLAS",
        "src/render/cpu_overlay.rs",
        &[
            "write_label_overlay_pixel",
            "label_overlay_display_linear",
            "blend_display_source_over",
        ],
    );
    require_contains(
        root,
        findings,
        "ARCH-LABEL-ATLAS",
        "src/scene/labels/font.rs",
        &[
            "DEFAULT_LABEL_FONT_BYTES",
            "include_bytes!(\"fonts/ScenaBasicLatin-Regular.ttf\")",
            "default_label_font_face",
        ],
    );
    require_contains(
        root,
        findings,
        "ARCH-LABEL-ATLAS",
        "src/render/cpu_strokes.rs",
        &[
            "draw_strokes_cpu",
            "stroke_coverage",
            "write_label_overlay_pixel",
        ],
    );
    require_contains(
        root,
        findings,
        "ARCH-LABEL-ATLAS",
        "src/render/gpu/strokes.wgsl",
        &["stroke_coverage", "distance_px", "half_width_px"],
    );
    forbid_contains(
        root,
        findings,
        "ARCH-LABEL-ATLAS",
        "src/scene/labels.rs",
        &[
            "LabelGlyphCell",
            "glyph_cells",
            "LabelFont::Bitmap",
            "pub fn bitmap",
            "bitmap_glyph_rasters",
            "bitmap_label_metrics",
        ],
    );
    if root.join("src/scene/labels/bitmap.rs").exists() {
        findings.push(Finding::new(
            "ARCH-LABEL-ATLAS",
            "src/scene/labels/bitmap.rs still exists; delete the removed 5x7 bitmap label path",
        ));
    }
    forbid_contains(
        root,
        findings,
        "ARCH-LABEL-ATLAS",
        "src/render/prepare/labels.rs",
        &["append_label_primitives", "push_prepared_label_primitive"],
    );
    forbid_contains(
        root,
        findings,
        "ARCH-LABEL-ATLAS",
        "src/browser_probe/workflows.rs",
        &["browser-bitmap-labels", "bitmap-5x7"],
    );
}
