use crate::app::prelude::*;

pub(crate) fn check_render_quality_reflection_contracts(root: &Path, findings: &mut Vec<Finding>) {
    require_contains(
        root,
        findings,
        "ARCH-RENDER-QUALITY",
        "src/render/quality/reflection.rs",
        &[
            "evaluate_reflection_region_quality",
            "reflection_structure_missing",
            "reflection_firefly_outliers",
            "max_firefly_fraction",
            "reflection_firefly_fraction",
        ],
    );
    require_contains(
        root,
        findings,
        "ARCH-RENDER-QUALITY",
        "src/render/quality/tests/reflection_quality.rs",
        &[
            "reflection_quality_known_bad_fireflies_fail_exact_reason_and_good_passes",
            "reflection_firefly_outliers",
            "max_firefly_fraction",
            "firefly_reflection_fixture",
            "structured_reflection_fixture",
        ],
    );
    require_contains(
        root,
        findings,
        "ARCH-RENDER-QUALITY",
        "tests/scena_cli_recipe.rs",
        &[
            "scena_recipe_render_verify_fails_missing_reflection_quality_on_cpu_and_gpu",
            "scena_recipe_render_verify_passes_grid_reflection_quality_on_cpu_and_gpu",
            "scena_recipe_render_verify_passes_screen_space_reflection_quality_on_cpu_and_gpu",
            "scena_recipe_render_verify_material_reflection_changes_target_pixels_on_cpu_and_gpu",
            "scena_recipe_render_verify_chrome_ibl_fireflies_are_filtered_on_cpu_and_gpu",
            "scena_recipe_render_chrome_ibl_near_mirror_matches_cpu_and_keeps_detail_on_gpu",
            "expect_quality.reflection.target",
            "material-reflection-delta-metrics.json",
            "chrome-ibl-firefly-metrics.json",
            "chrome-ibl-near-mirror-parity.json",
            "scena.chrome_ibl_near_mirror_parity_probe.v1",
            "sphere_gpu_r012_r000_rmse",
            "sphere_gpu_r025_r000_rmse",
            "gpu_mid012_luminance_range",
            "gpu_mid025_luminance_range",
            "expect_quality.reflection",
            "reflection_structure_missing",
            "reflection_firefly_outliers",
            "max_firefly_fraction",
        ],
    );
}
