use crate::app::prelude::*;
pub(crate) fn check_m6_browser_renderer_probe(root: &Path, findings: &mut Vec<Finding>) {
    require_contains(
        root,
        findings,
        "VISUAL-BROWSER-M6",
        "Cargo.toml",
        &["browser-probe = [\"viewer-element\"]"],
    );
    require_contains(
        root,
        findings,
        "VISUAL-BROWSER-M6",
        "package.json",
        &[
            "\"browser:scene-host-proof\": \"node tests/browser/scene_host_browser_proof.js\"",
            "\"cloudflare:demo\": \"node scripts/probe_cloudflare_demo.js\"",
            "\"cloudflare:materials\": \"node scripts/probe_cloudflare_material_presets.mjs\"",
        ],
    );
    require_contains(
        root,
        findings,
        "VISUAL-BROWSER-M6",
        ".github/workflows/ci.yml",
        &[
            "npm run browser:scene-host-proof",
            "npm run demo:build",
            "npm run cloudflare:demo -- http://127.0.0.1:18104/index.html",
            "npm run cloudflare:materials",
        ],
    );
    require_contains(
        root,
        findings,
        "VISUAL-BROWSER-M6",
        ".github/workflows/release.yml",
        &[
            "npm run browser:scene-host-proof",
            "npm run demo:build",
            "npm run cloudflare:demo -- http://127.0.0.1:18104/index.html",
            "npm run cloudflare:materials",
        ],
    );
    require_contains(
        root,
        findings,
        "VISUAL-BROWSER-M6",
        "scripts/probe_cloudflare_demo.js",
        &[
            "assertConnectorRenderedPixelsMoveDuringReplay",
            "assertDeploymentBundleConsistency",
            "deployed WASM checksum mismatch",
            "connector replay marker motion is not enough",
            "rendered connector pixels did not move",
            "changedPixels >= 128",
        ],
    );
    require_contains(
        root,
        findings,
        "VISUAL-BROWSER-M6",
        "tests/assets/browser-proof/round-e-cloudflare-material-proof.json",
        &[
            "\"proof_class\": \"round-e-cloudflare-material-proof\"",
            "\"url\": \"https://scena-demo.pages.dev/proof/?sample=material-presets\"",
            "\"status\": \"pass\"",
            "\"checksum_matches_build\": true",
            "\"per_material\"",
            "\"neighbor_pairs\"",
        ],
    );
    require_contains(
        root,
        findings,
        "VISUAL-BROWSER-M6",
        "tests/browser/scene_host_browser_proof.js",
        &[
            "phase2_ssao_only_changes_rendered_pixels",
            "ssao_only_delta",
            "phase2SsaoOnlyDelta",
            "ambient_occlusion_passes === 1",
            "bloom_passes === 0",
            "fxaa_passes === 0",
            "SCENA_BROWSER_REQUIRE_V3D",
            "REQUIRE_V3D_HARDWARE",
        ],
    );
    check_raw_webgl2_renderer_removed(root, findings);
    require_contains(
        root,
        findings,
        "VISUAL-BROWSER-M6",
        "src/browser_probe.rs",
        &[
            "m6RenderWebgl2Probe",
            "m6RenderWebgpuProbe",
            "m6RenderWorkflowProbe",
            "m6RenderDroppedFileProbe",
            "m6RenderMaterialVariantProbe",
            "m6RenderSurfaceLifecycleProbe",
            "m6RenderBenchmarkProbe",
            "m6RenderStateLifecycleProbe",
            "Renderer::from_surface_async",
            "prepare_with_assets",
            "browser_probe_readback_rgba8",
            "renderer-owned-gpu-copy",
            "scena.m6.browser_renderer_probe.v1",
            "m6CameraControlKitProbe",
            "scena.m6.camera_control_kit_browser_proof.v1",
        ],
    );
    require_contains(
        root,
        findings,
        "VISUAL-BROWSER-M6",
        "src/browser_probe/probes.rs",
        &[".render(&scene, camera)"],
    );
    require_contains(
        root,
        findings,
        "VISUAL-BROWSER-M6",
        "src/browser_probe/dropped_file.rs",
        &[
            "render_dropped_file_probe",
            "DroppedFileFetcher",
            "auto_frame_metadata",
            "viewer-level-auto-framing",
            "scena-viewer-drop-render",
            "add_perspective_camera_default_for",
            "project_world_point",
        ],
    );
    require_contains(
        root,
        findings,
        "VISUAL-BROWSER-M6",
        "src/browser_probe/material_variant.rs",
        &[
            "render_material_variant_probe",
            "material_variants_scene.gltf",
            "set_active_variant",
            "active_variant",
            "scena-viewer-material-variant-render",
        ],
    );
    require_contains(
        root,
        findings,
        "VISUAL-BROWSER-M6",
        "src/browser_probe/probes.rs",
        &[
            "scena.m6.browser_surface_lifecycle_probe.v1",
            "build_workflow_scene(\"material-textures\")",
            "RetainPolicy::OnContextLossOnly",
            "material_texture_bindings",
            "scena.m6.browser_benchmark_probe.v1",
            "surface-context-lifecycle",
        ],
    );
    require_contains(
        root,
        findings,
        "VISUAL-BROWSER-M6",
        "src/browser_probe/probes/state_lifecycle.rs",
        &[
            "scena.m6.browser_state_lifecycle_probe.v1",
            "dirty-transform",
            "dirty-material",
            "dirty-instance",
            "dirty-camera",
            "dirty-resize-dpr",
            "dirty-hover-selection",
            "dirty-animation-mixer",
            "context-recovery",
            "resource-lifetime",
            "idle-render-skipped",
        ],
    );
    require_contains(
        root,
        findings,
        "VISUAL-BROWSER-M6",
        "src/browser_probe/workflows.rs",
        &[
            "model-viewer",
            "non_ndc_camera_scene.gltf",
            "camera-framed-non-ndc",
            "depth-overlap",
            "depth-overlap-near-wins",
            "pbr-point-light",
            "pbr-spot-light",
            "pbr-normal-map",
            "pbr-environment",
            "pbr-material-extensions",
            "source-gltf-materials",
            "instancing",
            "picking-selection",
            "animation",
            "labels-helpers",
            "industrial-static-scene",
        ],
    );
    require_contains(
        root,
        findings,
        "VISUAL-BROWSER-M6",
        "src/browser_probe/workflows/pbr.rs",
        &[
            "browser-pbr-punctual-light",
            "browser-pbr-normal-map",
            "browser-pbr-environment-light",
            "browser-pbr-material-extension-composite",
            "with_dispersion_factor",
            "inline-radiance-hdr",
            "radiance_hdr_data_uri",
            "pbr-metallic-roughness",
        ],
    );
    require_contains(
        root,
        findings,
        "VISUAL-BROWSER-M6",
        "src/browser_probe/workflows/ergonomics/viewer.rs",
        &[
            "textured-connector-viewer",
            "pick_and_select_with_assets",
            "frame_all_with_assets",
            "with_base_color_texture",
        ],
    );
    require_contains(
        root,
        findings,
        "VISUAL-BROWSER-M6",
        "src/browser_probe/workflows/ergonomics/connectors.rs",
        &[
            "connector-magnet-preview",
            "connector_magnet_preview_scene",
            "preview_connector_magnet",
            "magnet_sequence",
            "css_class",
            "is_snap_ready",
        ],
    );
    require_contains(
        root,
        findings,
        "VISUAL-BROWSER-M6",
        "src/render/gpu/build.rs",
        &[
            "create_browser_canvas_surface",
            "wgpu::SurfaceTarget::Canvas",
            "raw_window_handle::WebDisplayHandle::new()",
            "Backend::WebGl2 => wgpu::Backends::GL",
            "wgpu::Limits::downlevel_webgl2_defaults()",
        ],
    );
    require_contains(
        root,
        findings,
        "VISUAL-BROWSER-M6",
        "src/browser_probe/report.rs",
        &[
            "physical_glass_transmission",
            "material_bindings",
            "material_texture_bindings",
            "material_sampler_bindings",
            "material_textures_missing_decoded_pixels",
        ],
    );
    require_contains(
        root,
        findings,
        "VISUAL-BROWSER-M6",
        "tests/browser/m6_rust_wasm_renderer_probe.html",
        &[
            "<meta name=\"viewport\"",
            "width=device-width",
            "m6_rust_wasm_renderer_probe_page.js",
        ],
    );
    require_contains(
        root,
        findings,
        "VISUAL-BROWSER-M6",
        "tests/browser/m6_rust_wasm_renderer_probe.js",
        &[
            "m6-rust-wasm-renderer-probe",
            "scenaM6RustWasmRendererProbe",
            "scenaM6RustWasmWorkflowProbe",
            "scenaM6RustWasmLifecycleProbe",
            "scenaM6RustWasmBenchmarkProbe",
            "scenaM6RustWasmStateLifecycleProbe",
            "/fixtures/",
            "webgl2",
            "webgpu",
            "chromiumLaunchArgs",
            "SCENA_BROWSER_BACKENDS",
            "SCENA_BROWSER_ALLOW_UNAVAILABLE",
            "NoAdapter",
            "m6-rust-wasm-renderer-probe.json",
            "assertModelViewerProof",
            "crypto.createHash",
            "fixture_sha256",
            "camera-framed-non-ndc",
            "non_ndc_camera_scene.gltf",
            "canvas_data_url",
            "screenshot_metadata",
            "assertDepthOverlapProof",
            "assertPunctualLightProof",
            "assertNormalMapProof",
            "assertEnvironmentLightProof",
            "assertMaterialExtensionProof",
            "assertMaterialTextureProof",
            "assertSourceGltfMaterialProof",
            "assertTexturedConnectorViewerProof",
            "assertConnectorMagnetPreviewProof",
            "assertScenaViewerElementProof",
            "runScenaViewerElementProof",
            "scena-viewer-element-browser-proof.png",
            "assertScenaViewerMobileA11yProof",
            "runScenaViewerMobileA11yProof",
            "scena-viewer-mobile-a11y-browser-proof.png",
            "assertCameraControlKitProof",
            "runCameraControlKitProof",
            "camera-control-kit-browser-proof.png",
            "progress_sequence",
            "drop_render_status",
            "drop_render_auto_frame_status",
            "viewer-level-auto-framing",
            "scena-viewer-drop-render",
            "variant_render_status",
            "scena-viewer-material-variant-render",
            "annotation_tracking_sequence",
            "annotation_update_visible",
            "inspector_fixture_schema",
            "SCENA_BROWSER_VIEWER_ELEMENT_ONLY",
            "scena.scena_viewer_element_browser_proof.v1",
            "scena.scena_viewer_mobile_a11y_browser_proof.v1",
            "scena.scena_viewer_inspector_snapshot.v1",
            "scena.m6.camera_control_kit_browser_proof.v1",
            "assertSurfaceLifecycleProbe",
            "assertNoScenaGpuValidationErrors",
            "scena wgpu uncaptured error",
            "material_texture_bindings < 5",
            "decoded_base_color_texture",
            "decoded_normal_texture",
            "decoded_emissive_texture",
            "depth-overlap",
            "depth-overlap-near-wins",
            "pbr-point-light",
            "pbr-spot-light",
            "pbr-normal-map",
            "pbr-environment",
            "browser-pbr-punctual-light",
            "browser-pbr-normal-map",
            "browser-pbr-environment-light",
            "material-textures",
            "source-gltf-materials",
            "MaterialTextureMissingDecodedPixels",
            "textured-connector-viewer",
            "connector-magnet-preview",
            "magnet_sequence",
            "scena-magnet-ready",
            "scena-magnet-out-of-range",
            "model-viewer",
            "instancing",
            "picking-selection",
            "animation",
            "labels-helpers",
            "industrial-static-scene",
        ],
    );
    require_contains(
        root,
        findings,
        "VISUAL-BROWSER-M6",
        "tests/browser/m6_rust_wasm_renderer_probe_page.js",
        &[
            "m6RenderWebgl2Probe",
            "defineScenaViewer",
            "m6CameraControlKitProbe",
            "m6RenderDroppedFileProbe",
            "m6RenderMaterialVariantProbe",
            "scenaViewerElementProbe",
            "scenaViewerMobileA11yProbe",
            "scenaCameraControlKitProbe",
            "scena.scena_viewer_element_browser_proof.v1",
            "scena.scena_viewer_mobile_a11y_browser_proof.v1",
            "loadInspectorSnapshot",
            "/fixtures/viewer/inspector_snapshot.json",
            "scena.scena_viewer_inspector_snapshot.v1",
            "scena.m6.camera_control_kit_browser_proof.v1",
            "scena-viewer-progress-rendered",
            "progress_sequence",
            "scena-viewer-file-drop",
            "scena-viewer-drop-error",
            "renderDroppedFileIntoViewer",
            "scena-viewer-drop-render",
            "drop_render_pixels_nonblack",
            "drop_render_auto_frame_status",
            "viewer-level-auto-framing",
            "renderSelectedVariantIntoViewer",
            "variant_render_green_dominant",
            "scena-viewer-material-variant-render",
            "scena-viewer-variant-change",
            "scena-viewer-annotations-rendered",
            "annotation_tracking_sequence",
            "annotation_update_visible",
            "scena-viewer-inspector-rendered",
            "scena-viewer-key-control",
            "scena-viewer-gesture-control",
            "pinch-zoom",
            "m6RenderWebgpuProbe",
            "m6RenderWorkflowProbe",
            "m6RenderSurfaceLifecycleProbe",
            "m6RenderBenchmarkProbe",
            "m6RenderStateLifecycleProbe",
            "readWebGl2Pixels",
            "preserveDrawingBuffer",
            "readCanvasPixels",
            "readRenderedPixels",
            "getImageData",
            "scenaM6RustWasmWorkflowProbe",
            "scenaM6RustWasmLifecycleProbe",
            "scenaM6RustWasmBenchmarkProbe",
            "scenaM6RustWasmStateLifecycleProbe",
            "screenshot_metadata",
            "device_pixel_ratio",
            "readRenderedPixelsWithRetry",
            "pixel_readback_attempts",
            "renderer_readback",
            "pixel_source",
            "renderer-owned-gpu-copy",
            "pixel_statistics",
            "nonblack",
            "left",
            "right",
        ],
    );
    forbid_contains(
        root,
        findings,
        "VISUAL-BROWSER-M6",
        "tests/m6_browser_renderer_parity.rs",
        &[
            "return;",
            "could not build on this lane; skipping",
            "could not render on this lane; skipping",
        ],
    );
    require_contains(
        root,
        findings,
        "VISUAL-BROWSER-M6",
        "tests/m6_browser_renderer_parity.rs",
        &[
            "browser_canvas_rgba8(&canvas).expect(\"WebGL2 canvas readback exists\")",
            "readPixels",
            "WebGL2 proof must include rendered pixels",
        ],
    );
    require_contains(
        root,
        findings,
        "VISUAL-BROWSER-M6",
        "tests/reference_image_regression_api.rs",
        &[
            "reference_image_regression_compares_real_renderer_output_to_committed_golden",
            "Renderer::headless(4, 4)",
            "renderer output matches committed golden",
        ],
    );
    require_contains(
        root,
        findings,
        "VISUAL-BROWSER-M6",
        "tests/placeholder_regression.rs",
        &[
            "agent_contract_fields_differ_across_distinct_scenes",
            "public_quality_knob_changes_renderer_state",
            "public_double_sided_material_knob_changes_pixels",
        ],
    );
    require_contains(
        root,
        findings,
        "VISUAL-BROWSER-M6",
        "tests/assets/viewer/inspector_snapshot.json",
        &[
            "scena.scena_viewer_inspector_snapshot.v1",
            "scena-viewer-inspector-fixture",
            "\"diagnostics\"",
            "\"stats\"",
            "\"FrameBounds\"",
            "\"drawCalls\"",
        ],
    );
    if let Ok(page_source) =
        fs::read_to_string(root.join("tests/browser/m6_rust_wasm_renderer_probe_page.js"))
        && page_source.contains("backend === \"webgpu\" ||")
    {
        findings.push(Finding::new(
            "VISUAL-BROWSER-M6",
            "tests/browser/m6_rust_wasm_renderer_probe_page.js must not auto-pass WebGPU \
             workflows without nonblack pixel evidence",
        ));
    }
    require_contains(
        root,
        findings,
        "VISUAL-BROWSER-M6",
        "src/render/gpu/prepare_resources_wasm.rs",
        &["target.backend == Backend::WebGpu"],
    );
    require_contains(
        root,
        findings,
        "VISUAL-BROWSER-M6",
        "docs/checklists/m6-browser-renderer-parity.md",
        &[
            "wasm-pack build --dev --target web --out-dir target/m6-browser-pkg . --features browser-probe",
            "node tests/browser/m6_rust_wasm_renderer_probe.js",
            "VISUAL-BROWSER-M6",
            "dirty-transform",
            "resource-lifetime",
            "idle-render-skipped",
        ],
    );
}

fn check_raw_webgl2_renderer_removed(root: &Path, findings: &mut Vec<Finding>) {
    for raw_binding in [
        "WebGl2RenderingContext",
        "WebGlBuffer",
        "WebGlProgram",
        "WebGlShader",
        "WebGlTexture",
    ] {
        forbid_contains(
            root,
            findings,
            "VISUAL-BROWSER-M6",
            "Cargo.toml",
            &[raw_binding],
        );
    }

    for retired_file in [
        "src/render/gpu/webgl2.rs",
        "src/render/gpu/webgl2_program.rs",
        "src/render/gpu/webgl2_camera.rs",
        "src/render/gpu/webgl2_lighting.rs",
        "src/render/gpu/webgl2_materials.rs",
        "src/render/gpu/webgl2_texture_set.rs",
        "src/render/gpu/webgl2_vertices.rs",
    ] {
        if root.join(retired_file).exists() {
            findings.push(Finding::new(
                "VISUAL-BROWSER-M6",
                format!("{retired_file} is a retired raw WebGL2 renderer file and must be deleted"),
            ));
        }
    }

    for rel in [
        "src/render/gpu.rs",
        "src/render/gpu/draw.rs",
        "src/render/gpu/build.rs",
        "src/render/gpu/lifecycle.rs",
        "src/render/gpu/debug.rs",
    ] {
        forbid_contains(
            root,
            findings,
            "VISUAL-BROWSER-M6",
            rel,
            &[
                "WebGl2RenderCache",
                "webgl2_render_cache",
                "webgl2_vertices",
                "prepare_canvas_vertices",
                "render_canvas",
                "WebGl2RenderingContext",
                "WebGlProgram",
                "WebGlShader",
                "compileShader",
                "linkProgram",
                "bufferData",
                "VERTEX_SHADER",
                "FRAGMENT_SHADER",
            ],
        );
    }
}
