use crate::app::prelude::*;
pub(crate) fn check_m6_browser_renderer_probe(root: &Path, findings: &mut Vec<Finding>) {
    require_contains(
        root,
        findings,
        "VISUAL-BROWSER-M6",
        "Cargo.toml",
        &["browser-probe"],
    );
    check_raw_webgl2_renderer_removed(root, findings);
    require_contains(
        root,
        findings,
        "VISUAL-BROWSER-M6",
        "src/browser_probe.rs",
        &[
            "m6RenderWebgl2Probe",
            "m6RenderWebgpuProbe",
            "m6RenderWorkflowProbe",
            "m6RenderSurfaceLifecycleProbe",
            "m6RenderBenchmarkProbe",
            "m6RenderStateLifecycleProbe",
            "Renderer::from_surface_async",
            "prepare_with_assets",
            "Renderer::render",
            "browser_probe_readback_rgba8",
            "renderer-owned-gpu-copy",
            "scena.m6.browser_renderer_probe.v1",
        ],
    );
    require_contains(
        root,
        findings,
        "VISUAL-BROWSER-M6",
        "src/browser_probe/probes.rs",
        &[
            "scena.m6.browser_surface_lifecycle_probe.v1",
            "build_workflow_scene(\"material-textures\")",
            "RetainPolicy::OnContextLossOnly",
            "material_texture_bindings",
            "scena.m6.browser_benchmark_probe.v1",
            "surface-context-lifecycle",
        ],
    );
    require_contains(
        root,
        findings,
        "VISUAL-BROWSER-M6",
        "src/browser_probe/probes/state_lifecycle.rs",
        &[
            "scena.m6.browser_state_lifecycle_probe.v1",
            "dirty-transform",
            "dirty-material",
            "dirty-instance",
            "dirty-camera",
            "dirty-resize-dpr",
            "dirty-hover-selection",
            "dirty-animation-mixer",
            "context-recovery",
            "resource-lifetime",
            "idle-render-skipped",
        ],
    );
    require_contains(
        root,
        findings,
        "VISUAL-BROWSER-M6",
        "src/browser_probe/workflows.rs",
        &[
            "model-viewer",
            "non_ndc_camera_scene.gltf",
            "camera-framed-non-ndc",
            "depth-overlap",
            "depth-overlap-near-wins",
            "pbr-point-light",
            "pbr-spot-light",
            "pbr-normal-map",
            "pbr-environment",
            "instancing",
            "picking-selection",
            "animation",
            "labels-helpers",
            "industrial-static-scene",
        ],
    );
    require_contains(
        root,
        findings,
        "VISUAL-BROWSER-M6",
        "src/browser_probe/workflows/pbr.rs",
        &[
            "browser-pbr-punctual-light",
            "browser-pbr-normal-map",
            "browser-pbr-environment-light",
            "inline-radiance-hdr",
            "radiance_hdr_data_uri",
            "pbr-metallic-roughness",
        ],
    );
    require_contains(
        root,
        findings,
        "VISUAL-BROWSER-M6",
        "src/browser_probe/workflows/ergonomics/viewer.rs",
        &[
            "textured-connector-viewer",
            "pick_and_select_with_assets",
            "frame_all_with_assets",
            "with_base_color_texture",
        ],
    );
    require_contains(
        root,
        findings,
        "VISUAL-BROWSER-M6",
        "src/render/gpu/build.rs",
        &[
            "create_browser_canvas_surface",
            "wgpu::SurfaceTarget::Canvas",
            "raw_window_handle::WebDisplayHandle::new()",
            "Backend::WebGl2 => wgpu::Backends::GL",
            "wgpu::Limits::downlevel_webgl2_defaults()",
        ],
    );
    require_contains(
        root,
        findings,
        "VISUAL-BROWSER-M6",
        "src/browser_probe/report.rs",
        &[
            "material_bindings",
            "material_texture_bindings",
            "material_sampler_bindings",
        ],
    );
    require_contains(
        root,
        findings,
        "VISUAL-BROWSER-M6",
        "tests/browser/m6_rust_wasm_renderer_probe.js",
        &[
            "m6-rust-wasm-renderer-probe",
            "scenaM6RustWasmRendererProbe",
            "scenaM6RustWasmWorkflowProbe",
            "scenaM6RustWasmLifecycleProbe",
            "scenaM6RustWasmBenchmarkProbe",
            "scenaM6RustWasmStateLifecycleProbe",
            "/fixtures/",
            "webgl2",
            "webgpu",
            "chromiumLaunchArgs",
            "SCENA_BROWSER_BACKENDS",
            "SCENA_BROWSER_ALLOW_UNAVAILABLE",
            "NoAdapter",
            "m6-rust-wasm-renderer-probe.json",
            "assertModelViewerProof",
            "crypto.createHash",
            "fixture_sha256",
            "camera-framed-non-ndc",
            "non_ndc_camera_scene.gltf",
            "canvas_data_url",
            "screenshot_metadata",
            "assertDepthOverlapProof",
            "assertPunctualLightProof",
            "assertNormalMapProof",
            "assertEnvironmentLightProof",
            "assertMaterialTextureProof",
            "assertTexturedConnectorViewerProof",
            "assertSurfaceLifecycleProbe",
            "assertNoScenaGpuValidationErrors",
            "scena wgpu uncaptured error",
            "material_texture_bindings < 5",
            "decoded_base_color_texture",
            "decoded_normal_texture",
            "decoded_emissive_texture",
            "depth-overlap",
            "depth-overlap-near-wins",
            "pbr-point-light",
            "pbr-spot-light",
            "pbr-normal-map",
            "pbr-environment",
            "browser-pbr-punctual-light",
            "browser-pbr-normal-map",
            "browser-pbr-environment-light",
            "material-textures",
            "textured-connector-viewer",
            "model-viewer",
            "instancing",
            "picking-selection",
            "animation",
            "labels-helpers",
            "industrial-static-scene",
        ],
    );
    require_contains(
        root,
        findings,
        "VISUAL-BROWSER-M6",
        "tests/browser/m6_rust_wasm_renderer_probe_page.js",
        &[
            "m6RenderWebgl2Probe",
            "m6RenderWebgpuProbe",
            "m6RenderWorkflowProbe",
            "m6RenderSurfaceLifecycleProbe",
            "m6RenderBenchmarkProbe",
            "m6RenderStateLifecycleProbe",
            "readWebGl2Pixels",
            "preserveDrawingBuffer",
            "readCanvasPixels",
            "readRenderedPixels",
            "getImageData",
            "scenaM6RustWasmWorkflowProbe",
            "scenaM6RustWasmLifecycleProbe",
            "scenaM6RustWasmBenchmarkProbe",
            "scenaM6RustWasmStateLifecycleProbe",
            "screenshot_metadata",
            "device_pixel_ratio",
            "readRenderedPixelsWithRetry",
            "pixel_readback_attempts",
            "renderer_readback",
            "pixel_source",
            "renderer-owned-gpu-copy",
            "pixel_statistics",
            "nonblack",
        ],
    );
    if let Ok(page_source) =
        fs::read_to_string(root.join("tests/browser/m6_rust_wasm_renderer_probe_page.js"))
        && page_source.contains("backend === \"webgpu\" ||")
    {
        findings.push(Finding::new(
            "VISUAL-BROWSER-M6",
            "tests/browser/m6_rust_wasm_renderer_probe_page.js must not auto-pass WebGPU \
             workflows without nonblack pixel evidence",
        ));
    }
    require_contains(
        root,
        findings,
        "VISUAL-BROWSER-M6",
        "src/render/gpu.rs",
        &["target.backend == Backend::WebGpu"],
    );
    require_contains(
        root,
        findings,
        "VISUAL-BROWSER-M6",
        "docs/checklists/m6-browser-renderer-parity.md",
        &[
            "wasm-pack build --dev --target web --out-dir target/m6-browser-pkg . --features browser-probe",
            "node tests/browser/m6_rust_wasm_renderer_probe.js",
            "VISUAL-BROWSER-M6",
            "dirty-transform",
            "resource-lifetime",
            "idle-render-skipped",
        ],
    );
}

fn check_raw_webgl2_renderer_removed(root: &Path, findings: &mut Vec<Finding>) {
    for raw_binding in [
        "WebGl2RenderingContext",
        "WebGlBuffer",
        "WebGlProgram",
        "WebGlShader",
        "WebGlTexture",
    ] {
        forbid_contains(
            root,
            findings,
            "VISUAL-BROWSER-M6",
            "Cargo.toml",
            &[raw_binding],
        );
    }

    for retired_file in [
        "src/render/gpu/webgl2.rs",
        "src/render/gpu/webgl2_program.rs",
        "src/render/gpu/webgl2_camera.rs",
        "src/render/gpu/webgl2_lighting.rs",
        "src/render/gpu/webgl2_materials.rs",
        "src/render/gpu/webgl2_texture_set.rs",
        "src/render/gpu/webgl2_vertices.rs",
    ] {
        if root.join(retired_file).exists() {
            findings.push(Finding::new(
                "VISUAL-BROWSER-M6",
                format!("{retired_file} is a retired raw WebGL2 renderer file and must be deleted"),
            ));
        }
    }

    for rel in [
        "src/render/gpu.rs",
        "src/render/gpu/draw.rs",
        "src/render/gpu/build.rs",
        "src/render/gpu/lifecycle.rs",
        "src/render/gpu/debug.rs",
    ] {
        forbid_contains(
            root,
            findings,
            "VISUAL-BROWSER-M6",
            rel,
            &[
                "WebGl2RenderCache",
                "webgl2_render_cache",
                "webgl2_vertices",
                "prepare_canvas_vertices",
                "render_canvas",
                "WebGl2RenderingContext",
                "WebGlProgram",
                "WebGlShader",
                "compileShader",
                "linkProgram",
                "bufferData",
                "VERTEX_SHADER",
                "FRAGMENT_SHADER",
            ],
        );
    }
}
