use crate::app::prelude::*;

pub(crate) fn check_m9_ci_release_lanes(root: &Path, findings: &mut Vec<Finding>) {
    require_contains(
        root,
        findings,
        "RELEASE-CI-M9",
        ".github/workflows/ci.yml",
        &[
            "linux-native-vulkan",
            "linux-browser-webgl2",
            "linux-browser-webgpu",
            "wasm32",
            "macos-metal",
            "windows-dx12",
            "headless-4k-performance",
            "dtolnay/rust-toolchain@1.93.1",
            "components: rustfmt, clippy",
            "node-version: \"20.20.0\"",
            "PLAYWRIGHT_VERSION: \"1.59.1\"",
            "BINARYEN_VERSION: \"129.0.0\"",
            "BROTLI_CLI_VERSION: \"2.1.1\"",
            "npm ci",
            "npx playwright install chromium --with-deps",
            "cargo install wasm-pack --version 0.14.0",
            "wasm-pack build --release --target web --out-dir target/m9-browser-pkg . --features browser-probe",
            "npm run wasm:size",
            "Platform parity gates",
            "cargo fmt --check",
            "cargo clippy --all-targets -- -D warnings",
            "cargo test --test m9_platform_release",
            "m9_dedicated_headless_4k_benchmark_writes_release_blocker_artifact",
            "SCENA_BROWSER_BACKENDS: webgl2",
            "SCENA_BROWSER_BACKENDS: webgpu",
            "SCENA_BROWSER_ALLOW_UNAVAILABLE: \"1\"",
            "cargo run -p xtask -- doctor --full",
            "premerge-release-readiness",
            "Download release lane artifacts",
            "Release readiness drift check",
            "actions/download-artifact@v4",
            "target/release-artifacts",
            "stage-release-artifacts target/release-artifacts target/gate-artifacts",
            "SCENA_RELEASE_ARTIFACT_ROOT: target/gate-artifacts",
            "cargo run -p xtask -- release-readiness",
            "RUSTDOCFLAGS: \"-D warnings\"",
            "cargo doc --no-deps --all-features",
            "release-lane-artifact",
            "target/gate-artifacts/**",
            "if-no-files-found: error",
        ],
    );
    forbid_contains(
        root,
        findings,
        "RELEASE-CI-M9",
        ".github/workflows/ci.yml",
        &["if-no-files-found: ignore", "merge-multiple: true"],
    );
    forbid_contains(
        root,
        findings,
        "RELEASE-CI-M9",
        ".github/workflows/release.yml",
        &["merge-multiple: true"],
    );
    require_contains(
        root,
        findings,
        "RELEASE-CI-M9",
        ".github/workflows/release.yml",
        &[
            "linux-native-vulkan",
            "linux-browser-webgl2",
            "linux-browser-webgpu",
            "wasm32-unknown-unknown",
            "macos-metal",
            "windows-dx12",
            "headless-4k-performance",
            "cargo publish --dry-run",
            "cargo publish",
            "gh release create",
            "cargo run -p xtask -- release-readiness",
            "actions/download-artifact@v4",
            "SCENA_RELEASE_ARTIFACT_ROOT",
            "Stage release artifacts for readiness",
            "stage-release-artifacts target/release-artifacts target/gate-artifacts",
            "SCENA_BROWSER_BACKENDS: webgl2",
            "SCENA_BROWSER_BACKENDS: webgpu",
            "components: rustfmt, clippy",
            "needs:",
            "release-lane-artifact",
        ],
    );
    require_contains(
        root,
        findings,
        "RELEASE-CI-M9",
        "package.json",
        &[
            "\"node\": \"20.20.0\"",
            "\"npm\": \"10.8.2\"",
            "\"playwright\": \"1.59.1\"",
            "\"binaryen\": \"129.0.0\"",
            "\"brotli-cli\": \"2.1.1\"",
            "\"browser:m6\"",
            "\"wasm:size\"",
        ],
    );
    require_contains(
        root,
        findings,
        "RELEASE-CI-M9",
        "tests/release/m9_wasm_size_gate.js",
        &[
            "required_features: [\"browser-probe\"]",
            "m6RenderWebgl2Probe",
            "m6RenderWebgpuProbe",
            "feature_enabled_probe_exports_present",
            "WASM size gate must measure the browser-probe renderer bundle",
        ],
    );
    require_contains(
        root,
        findings,
        "RELEASE-CI-M9",
        "package-lock.json",
        &["\"playwright\": \"1.59.1\"", "\"version\": \"1.59.1\""],
    );
    require_contains(
        root,
        findings,
        "RELEASE-CI-M9",
        "Cargo.toml",
        &[
            "repository = \"https://github.com/johannesPettersson80/scena\"",
            "authors = [\"Johannes Pettersson <johannes_salomon@hotmail.com>\"]",
            "documentation = \"https://docs.rs/scena\"",
            "license = \"MIT OR Apache-2.0\"",
            "readme = \"README.md\"",
            "keywords = [\"renderer\", \"scene-graph\", \"gltf\", \"webgpu\", \"wasm\"]",
            "categories = [\"graphics\", \"rendering\", \"wasm\"]",
            "CHANGELOG.md",
            "docs/**",
            "[package.metadata.docs.rs]",
            "wasm32-unknown-unknown",
        ],
    );
    require_contains_in_xtask_app_tree(
        root,
        findings,
        "RELEASE-CI-M9",
        &[
            "release-lane-artifact",
            "stage-release-artifacts",
            "scena.release_lane.v1",
            "content_ok",
            "command_records",
            "release_lane_command_records",
            "release_lane_measured_command_records",
            "require_release_lane_artifact_evidence",
            "stage_release_artifacts",
            "duration_ms",
            "measurement_source",
            "failure_log_path",
            "failure_log_sha256",
            "release_lane_content_ok",
            "browser_probe_release_proof_passes",
            "REQUIRED_NATIVE_GPU_RENDER_ARTIFACT_SUFFIXES",
            "require_native_gpu_render_proof",
            "native_gpu_render_proof_passes",
            "pbr_light_render_proof_passes",
            "native-pbr-punctual-light",
            "pbr-directional-red.ppm",
            "pbr-point-green.ppm",
            "pbr-spot-blue.ppm",
            "CPU fallback artifacts cannot satisfy GPU release claims",
            "release_readiness_rejects_cpu_fallback_native_render_artifact",
            "release_readiness_rejects_native_render_artifact_without_pbr_light_proof",
            "release_readiness_accepts_native_render_artifact_with_pbr_light_proof",
            "release_readiness_rejects_stale_timestamped_artifact",
            "release_readiness_rejects_constant_ppm_visual_artifact",
            "release_readiness_rejects_factory_contract_capability_rows",
            "release_readiness_rejects_benchmark_artifact_without_stored_baseline_comparison",
            "release_readiness_rejects_benchmark_regression_against_stored_baseline",
            "release_readiness_accepts_benchmark_artifact_with_passed_baseline_comparison",
            "reject_stale_json_timestamp",
            "reject_constant_ppm_artifact",
            "reject_unmeasured_capability_matrix_rows",
            "REQUIRED_BENCHMARK_ARTIFACT_SUFFIXES",
            "m9-benchmarks-4k.json",
            "require_benchmark_baseline_comparison",
            "REQUIRED_RENDERED_OUTPUT_METADATA_ARTIFACT_SUFFIXES",
            "require_rendered_output_screenshot_metadata",
            "require_screenshot_metadata_entry",
            "release_readiness_rejects_rendered_output_without_screenshot_metadata",
            "release_readiness_accepts_rendered_output_with_screenshot_metadata",
            "release_readiness_rejects_release_lane_artifact_without_measured_command_duration",
            "release_readiness_rejects_release_lane_artifact_with_failed_command_record",
            "MIN_BENCHMARK_SAMPLE_COUNT",
            "release_lane_artifact_status_requires_native_gpu_content_proof",
            "release_lane_artifact_status_requires_browser_probe_passed_status",
            "visual-proof/waterbottle-gpu.json",
            "visual-proof/browser-webgpu.json",
            "visual-proof/browser-webgl2.json",
            "visual-proof/native-gpu.json",
        ],
    );
    require_contains(
        root,
        findings,
        "RELEASE-CI-M9",
        "scripts/release_lane_command.sh",
        &[
            "target/gate-artifacts/release-lanes",
            "duration_ms",
            "failure_log_sha256",
            "ci-wrapper",
        ],
    );
    require_contains(
        root,
        findings,
        "RELEASE-CI-M9",
        ".github/workflows/ci.yml",
        &["scripts/release_lane_command.sh", "release-lane-artifact"],
    );
    require_contains(
        root,
        findings,
        "RELEASE-CI-M9",
        ".github/workflows/release.yml",
        &["scripts/release_lane_command.sh", "release-lane-artifact"],
    );
    require_contains(
        root,
        findings,
        "RELEASE-CI-M9",
        "tests/m9_platform_release.rs",
        &[
            "m9_platform_rendered_output_suite_writes_release_artifacts",
            "m9_capability_matrix_artifact_covers_required_lanes",
            "m9_surface_context_loss_artifact_records_required_sequence",
            "m9-benchmarks.json",
            "m9-benchmarks-4k.json",
            "m9-capability-matrix.json",
            "scena.m9.platform_render.v1",
            "scena.capabilities.v1",
            "linux-native-vulkan",
            "macos-metal",
            "windows-dx12",
            "default-scene.ppm",
            "static-gltf.ppm",
            "pbr-directional-red.ppm",
            "pbr-point-green.ppm",
            "pbr-spot-blue.ppm",
            "render_pbr_light_suite_platform",
            "native-pbr-punctual-light",
            "PbrLightKind::DirectionalRed",
            "PbrLightKind::PointGreen",
            "PbrLightKind::SpotBlue",
            "m9_asset_provenance_records_source_path_and_hash",
            "m9_static_gltf_proof_uses_non_ndc_camera_framed_asset",
            "STATIC_GLTF_PROOF_FIXTURE",
            "non_ndc_camera_scene.gltf",
            "\"proof_class\": \"harness-smoke\"",
            "\"production_claim\": false",
            "production_claim_for_gpu",
            "static_gltf_proof_class",
            "cpu-fallback-camera-framed-non-ndc",
            "cpu fallback is diagnostic only and never satisfies GPU rendered-output claims",
            "\"gpu_proof\"",
            "\"asset_provenance\"",
            "\"source_hash\"",
            "m9_cpu_fallback_artifacts_do_not_claim_gpu_rendered_output",
            "m9_screenshot_metadata_records_renderer_color_and_tolerance_contract",
            "screenshot_renderer_settings",
            "screenshot_color_management",
            "screenshot_tolerance_metadata",
            "\"renderer_settings\"",
            "\"color_management\"",
            "\"tolerance\"",
            "GpuAdapterReport",
            "AdapterLimitsReport",
            "m9_adapter_metadata_records_actual_gpu_identity_when_available",
            "gpu_adapter_report",
            "adapter_metadata",
            "\"adapter\"",
            "\"features\"",
            "\"limits\"",
            "\"driver\"",
            "\"commit\"",
            "\"timestamp_unix_seconds\"",
            "\"test_names\"",
            "\"artifact_paths\"",
            "native-rendered-output-smoke",
            "srgb8-after-aces",
            "BENCHMARK_BASELINE_PATH",
            "BENCHMARK_SAMPLE_COUNT: usize = 100",
            "m9_benchmark_rows_use_distribution_not_single_sample",
            "m9_benchmark_rows_record_stored_baseline_comparison",
            "m9_dedicated_headless_4k_benchmark_writes_release_blocker_artifact",
            "m9_benchmark_baseline_comparison_fails_significant_regressions",
            "apply_benchmark_baselines",
            "benchmark_baseline_for_row",
            "tests/fixtures/m9-baselines.json",
            "\"baseline_comparison\"",
            "\"baseline_sha256\"",
            "deferred-to-dedicated-performance-lane",
            "\"sample_count\"",
            "\"p50_frame_ms\"",
            "\"p95_frame_ms\"",
            "\"min_frame_ms\"",
            "\"max_frame_ms\"",
            "\"stddev_frame_ms\"",
            "\"fixture\"",
            "\"sample_count_policy\"",
            "\"status\": \"incomplete\"",
            "measurement_source",
            "capability_matrix_row",
            "lane_capability_from_artifact",
            "lane-renderer-runtime",
            "missing_lane_capability",
            "missing-lane-artifact",
            "no factory capability constants are accepted as platform proof",
        ],
    );
    forbid_contains(
        root,
        findings,
        "RELEASE-CI-M9",
        "tests/m9_platform_release.rs",
        &["factory-contract"],
    );
    forbid_contains(
        root,
        findings,
        "RELEASE-CI-M9",
        "tests/m9_platform_release.rs",
        &["\"status\": \"passed\",\n        \"lanes\": [\n            lane_capability"],
    );
    forbid_contains(
        root,
        findings,
        "RELEASE-CI-M9",
        "tests/m9_platform_release.rs",
        &["\"production_claim\": true"],
    );
}

pub(crate) fn check_m10_claim_audit_contract(root: &Path, findings: &mut Vec<Finding>) {
    require_contains_in_xtask_app_tree(
        root,
        findings,
        "CLAIM-AUDIT-M10",
        &[
            "claim-audit",
            "m10-claim-audit.json",
            "scena.m10.claim_audit.v1",
            "required_final_gates",
            "release-readiness",
            "REQUIRED_RELEASE_ARTIFACT_SUFFIXES",
        ],
    );
    require_contains(
        root,
        findings,
        "CLAIM-AUDIT-M10",
        "docs/checklists/m10-threejs-replacement-acceptance.md",
        &["m10-claim-audit.json", "claim audit"],
    );
    require_contains(
        root,
        findings,
        "CLAIM-AUDIT-M10",
        "docs/api/m10-public-api-diff.md",
        &[
            "M10 Public API Diff From M5 Baseline",
            "Renderer::diagnose_scene",
            "AssetLoadControl",
            "AssetError::UnsupportedTextureFormat",
            "Semver Decision",
        ],
    );
    require_contains(
        root,
        findings,
        "CLAIM-AUDIT-M10",
        "docs/release-notes/v1.0.0.md",
        &["scena v1.0.0 Release Notes", "Scope", "Install"],
    );
}

pub(crate) fn require_contains_in_xtask_app_tree(
    root: &Path,
    findings: &mut Vec<Finding>,
    rule: &'static str,
    needles: &[&str],
) {
    let files = xtask_source_files(root)
        .into_iter()
        .filter(|rel| path_to_forward_slash(rel).starts_with("crates/xtask/src/app"))
        .collect::<Vec<_>>();
    for needle in needles {
        let found = files.iter().any(|rel| {
            fs::read_to_string(root.join(rel))
                .map(|text| text.contains(needle))
                .unwrap_or(false)
        });
        if !found {
            findings.push(Finding::new(
                rule,
                format!(
                    "crates/xtask/src/app/**/*.rs is missing required contract text '{needle}'"
                ),
            ));
        }
    }
}
