use crate::app::prelude::*;

pub(crate) fn check_m7_inspection_contracts(root: &Path, findings: &mut Vec<Finding>) {
    require_contains(
        root,
        findings,
        "ERGONOMICS-M7",
        "src/render/offscreen.rs",
        &["pub fn screenshot_rgba8", "self.read_pixels()"],
    );
    require_contains(
        root,
        findings,
        "ERGONOMICS-M7",
        "src/scene/inspection.rs",
        &[
            "pub struct SceneInspectionReport",
            "pub struct SceneNodeInspection",
            "pub struct SceneDrawInspection",
            "pub struct SceneCameraFrustumInspection",
            "pub struct SceneMaterialInspection",
            "pub struct SceneTextureInspection",
            "pub struct SceneNormalInspection",
            "pub fn inspect_with_assets",
            "pub fn draw_list",
            "pub fn camera_frustums",
            "pub fn normal_overlays",
            "pub const fn camera_count",
            "pub const fn light_count",
            "pub const fn anchor_count",
            "pub const fn connector_count",
            "pub const fn mesh_geometry",
            "pub const fn mesh_material",
            "pub const fn material_preview",
            "world_transform: self.world_transform(node_key).unwrap_or(node.transform)",
            "pub const fn base_color_texture",
            "pub const fn source_format",
            "pub const fn decoded_dimensions",
            "pub const fn primitive_count",
            "pub const fn world_transform",
            "pub const fn corners",
            "pub fn segments",
            "pub const fn has_base_color_texture",
            "pub const fn camera",
            "pub const fn light",
            "pub const fn bounds",
        ],
    );
    require_contains(
        root,
        findings,
        "ERGONOMICS-M7",
        "src/scene/picking.rs",
        &[
            "pub fn pick(",
            "pub fn pick_with_assets",
            "pub fn pick_pointer",
            "pub fn pick_and_select",
            "pub fn pick_and_select_with_assets",
            "pub fn pick_and_hover",
            "pub fn pick_and_hover_with_assets",
            "pub fn set_hover_target",
            "pub fn set_primary_selection_target",
        ],
    );
    require_contains(
        root,
        findings,
        "ERGONOMICS-M7",
        "tests/first_render_api.rs",
        &[
            "first_render_gltf_headless_loads_frames_prepares_and_renders",
            "headless_gltf_viewer_builder_loads_frames_lights_and_renders",
            "headless_gltf_viewer_builder_can_attach_environment_and_report_diagnostics",
            "headless_gltf_viewer_builder_can_build_on_change_render_loop",
            "with_default_light",
            "with_default_environment",
            "on_change",
            "render_next_frame",
            "first.outcome().draw_calls > 0",
            "first.import().roots()",
            "screenshot_rgba8",
        ],
    );
    require_contains(
        root,
        findings,
        "ERGONOMICS-M7",
        "src/scene/view.rs",
        &[
            "pub fn frame_all_with_assets",
            "pub fn frame_node_with_assets",
            "asset_backed_scene_bounds_world",
            "asset_backed_node_subtree_bounds_world",
            "world_transform(target)",
            "world_transform(camera_node)",
            "inverse_unit_quat",
            "local_transform_for_world",
            "local_transform_from_world",
            "NonInvertibleParentTransform",
        ],
    );
    require_contains(
        root,
        findings,
        "ERGONOMICS-M7",
        "tests/m7_threejs_ergonomics.rs",
        &[
            "m7_frame_all_with_assets_frames_direct_mesh_bounds_without_manual_bounds_math",
            "m7_frame_all_with_assets_frames_instance_bounds_without_manual_bounds_math",
            "m7_frame_node_with_assets_frames_direct_mesh_without_manual_bounds_math",
            "m7_pick_with_assets_hits_direct_mesh_without_legacy_renderable",
            "m7_pick_with_assets_hits_instance_set_without_manual_triangles",
            "m7_pick_and_select_with_assets_updates_interaction_for_direct_mesh",
            "m7_pick_with_assets_hits_imported_gltf_mesh_without_manual_triangles",
            "m7_orbit_controls_keep_framed_asset_visible_after_camera_distance_change",
            "m7_scene_inspection_with_assets_reports_material_preview_metadata",
            "m7_scene_inspection_with_assets_reports_draw_list_entries",
            "m7_scene_inspection_reports_camera_frustum_debug_geometry",
            "m7_scene_inspection_reports_normal_debug_segments",
            "m7_scene_inspection_reports_local_and_world_transforms_for_nested_nodes",
            "m7_frame_nested_camera_preserves_requested_world_camera_pose",
            "texture_preview.decoded_dimensions()",
            "frame_all_with_assets",
            "frame_node_with_assets",
            "pick_with_assets",
            "pick_and_select_with_assets",
        ],
    );
    require_contains(
        root,
        findings,
        "ERGONOMICS-M7",
        "examples/scene_inspection.rs",
        &[
            "scene.inspect",
            "scene.inspect_with_assets",
            "visible_drawable_count",
            "camera_count",
            "camera_frustums",
            "normal_overlays",
            "connector_count",
            "draw_list",
            "mesh_geometry",
            "mesh_material",
            "material_preview",
            "primitive_count",
            "node.world_transform()",
            "world_transform",
            "node.kind()",
        ],
    );
    require_contains(
        root,
        findings,
        "ERGONOMICS-M7",
        "tests/m7_threejs_ergonomics.rs",
        &[
            "create_static_batch",
            "pick_and_select",
            "pick_and_hover",
            "set_hover_target",
            "set_primary_selection_target",
            "set_camera_layer_mask",
            "SurfaceViewport",
            "ImportAnchorDebugMetadata",
            "with_damping",
            "m7_beginner_scene_diagnostics_explain_invisible_setups",
            "GeometryDesc::normal_lines",
            "m7_error_display_snapshots_cover_beginner_recovery_paths",
            "m7_diagnostics_expose_typed_actionable_suggested_fixes",
            "m7_renderer_capability_report_exports_backend_adapter_and_diagnostics",
            "suggested_fix",
            "m7_viewer_operations_dirty_prepare_without_persistent_resource_growth",
            "m7_benchmark_artifact_writes_required_viewer_workflow_rows",
            "m7-workflow-benchmarks.json",
            "scena.m7.workflow_benchmarks.v1",
            "create_static_batch_with_report",
            "picking_debug_instances",
            "m7_scene_inspection_feature_reports_reproducible_metadata",
            "m7_scene_inspection_reports_local_and_world_transforms_for_nested_nodes",
            "camera_count",
            "mesh_geometry",
            "mesh_material",
            "node.camera()",
            "m7_import_exposes_source_units_and_coordinate_system_for_placement_diagnostics",
            "m7_import_diagnostic_overlays_expose_source_units_and_coordinate_system",
            "m7_replacement_import_rebinds_stable_anchor_and_connector_names",
            "m7_z_up_import_connector_basis_converts_before_connection_solving",
            "m7_left_handed_import_connector_rejects_instead_of_mirroring_silently",
            "m7_left_handed_mesh_import_fails_closed_until_winding_policy_exists",
            "m7_three_imported_objects_connect_into_assembly_without_raw_matrix_math",
            "m7_renderable_parent_world_transform_drives_rendered_placement",
            "m7_mesh_parent_world_transform_drives_rendered_placement",
            "m7_camera_look_at_nested_target_uses_world_transform",
            "m7_camera_look_at_point_nested_camera_uses_world_position",
            "m7_bounds_helpers_on_nested_nodes_preserve_requested_world_placement",
            "renderable_scene_with_parent_transform",
            "mesh_scene_with_parent_transform",
        ],
    );
}
