use crate::app::prelude::*;

pub(crate) fn check_renderer_truth_webgl2_contracts(root: &Path, findings: &mut Vec<Finding>) {
    require_contains(
        root,
        findings,
        "ARCH-RENDER-TRUTH",
        "src/render/gpu/webgl2.rs",
        &[
            "camera_uniforms",
            "bind_camera_uniforms",
            "WebGl2CameraUniformUpload",
            "bind_material_texture",
            "PrimitiveDrawBatch",
            "draw_batch_hash",
            "uniform4f",
            "uniform1i",
        ],
    );
    require_contains(
        root,
        findings,
        "ARCH-RENDER-TRUTH",
        "src/render/gpu/webgl2_camera.rs",
        &[
            "world_from_model",
            "normal_from_model",
            "view_from_world",
            "clip_from_view",
            "clip_from_world",
            "camera_position_exposure",
            "viewport_near_far",
            "color_management",
            "bind_camera_uniforms",
            "uniform_matrix4fv_with_f32_array",
        ],
    );
    require_contains(
        root,
        findings,
        "ARCH-RENDER-TRUTH",
        "src/render/gpu/webgl2_program.rs",
        &[
            "uniform mat4 world_from_model",
            "uniform mat4 normal_from_model",
            "uniform mat4 view_from_world",
            "uniform mat4 clip_from_view",
            "uniform mat4 clip_from_world",
            "uniform vec4 camera_position_exposure",
            "uniform vec4 viewport_near_far",
            "uniform vec4 color_management",
            "uniform vec4 directional_light_direction_intensity",
            "uniform vec4 point_light_position_intensity",
            "uniform vec4 spot_light_direction_cones",
            "uniform vec4 environment_diffuse_intensity",
            "uniform vec4 environment_specular_intensity",
            "pbrLightContribution",
            "pbrEnvironmentLighting",
            "fresnelSchlick",
            "distributionGgx",
            "geometrySmith",
            "uniform vec4 base_color_uv_offset_scale",
            "uniform vec4 base_color_uv_rotation",
            "uniform sampler2D base_color_texture",
            "in vec3 normal",
            "in vec4 tangent",
            "in vec2 tex_coord0",
            "in vec4 v_tangent",
            "in vec2 v_tex_coord0",
            "v_tangent.w",
            "normal_sample_tangent_space.x * world_tangent + normal_sample_tangent_space.y * bitangent + normal_sample_tangent_space.z * world_normal",
            "texture(base_color_texture, transformed_uv)",
            "base.a < metallic_roughness_alpha.z",
            "discard;",
            "webgl2_fragment_shader_discards_alpha_masked_fragments",
            "clip_from_view * view_from_world * world_position",
            "mat3(normal_from_model) * normal",
            "webgl2_vertex_shader_consumes_model_normal_view_and_projection_uniforms",
            "webgl2_fragment_shader_consumes_gpu_punctual_light_uniforms",
            "webgl2_fragment_shader_consumes_gpu_environment_light_uniforms",
            "webgl2_shader_builds_tangent_space_normal_from_normal_map",
        ],
    );
    require_contains(
        root,
        findings,
        "ARCH-RENDER-TRUTH",
        "src/render/gpu/webgl2_lighting.rs",
        &[
            "WebGl2LightingUniformLocations",
            "query_lighting_uniform_locations",
            "bind_lighting_uniforms",
            "directional_light_direction_intensity",
            "point_light_position_intensity",
            "spot_light_direction_cones",
            "spot_light_cone_range",
            "environment_diffuse_intensity",
            "environment_specular_intensity",
        ],
    );
    require_contains(
        root,
        findings,
        "ARCH-RENDER-TRUTH",
        "src/render/gpu/webgl2_materials.rs",
        &[
            "create_material_texture",
            "upload_material_texture_if_dirty",
            "MaterialTextureUpload::from_base_color_texture",
            "upload.sampler.wrap_s()",
            "upload.sampler.wrap_t()",
            "webgl2_wrap_mode",
            "webgl2_filter_mode",
            "webgl2_filter_uses_mipmaps",
            "tex_image_2d_with_i32_and_i32_and_i32_and_format_and_type_and_opt_u8_array",
        ],
    );
    forbid_contains(
        root,
        findings,
        "ARCH-RENDER-TRUTH",
        "src/render/gpu/output.rs",
        &["out.position = vec4<f32>(in.position, 1.0);"],
    );
    forbid_contains(
        root,
        findings,
        "ARCH-RENDER-TRUTH",
        "src/render/gpu/webgl2.rs",
        &["gl_Position = vec4(position, 1.0);"],
    );
    forbid_contains(
        root,
        findings,
        "ARCH-RENDER-TRUTH",
        "src/render/gpu/webgl2_program.rs",
        &["gl_Position = vec4(position, 1.0);"],
    );
    forbid_contains(
        root,
        findings,
        "ARCH-RENDER-TRUTH",
        "src/render/gpu/depth.rs",
        &["return vec4<f32>(in.position, 1.0);"],
    );
}
