use super::{SCHEMA_CATALOG_SCHEMA_V1, SCHEMA_ENTRY_SCHEMA_V1};
use crate::diagnostics::nearest_name_candidates;

pub(super) fn schema_fixture_json(schema: &str) -> Option<&'static str> {
    schema_fixture_map()
        .iter()
        .find_map(|(candidate, fixture)| (*candidate == schema).then_some(*fixture))
}

pub fn nearest_schema_name(input: &str) -> Option<&'static str> {
    let candidate = nearest_name_candidates(
        input,
        schema_fixture_map().iter().map(|(schema, _)| *schema),
        1,
    )
    .into_iter()
    .next()?;
    schema_fixture_map()
        .iter()
        .find_map(|(schema, _)| (*schema == candidate).then_some(*schema))
}

fn schema_fixture_map() -> &'static [(&'static str, &'static str)] {
    &[
        (
            "scena.agent_guide.v1",
            include_str!("../../tests/assets/stable-contracts/agent_guide.v1.json"),
        ),
        (
            "scena.contract_validation.v1",
            include_str!("../../tests/assets/stable-contracts/contract_validation.v1.json"),
        ),
        (
            "scena.json_schema_export.v1",
            include_str!("../../tests/assets/stable-contracts/json_schema_export.v1.json"),
        ),
        (
            SCHEMA_CATALOG_SCHEMA_V1,
            include_str!("../../tests/assets/stable-contracts/schema_catalog.v1.json"),
        ),
        (
            SCHEMA_ENTRY_SCHEMA_V1,
            include_str!("../../tests/assets/stable-contracts/schema_entry.v1.json"),
        ),
        (
            "scena.field_model.v1",
            include_str!("../../tests/assets/stable-contracts/field_model.v1.json"),
        ),
        (
            "scena.recipe_patch.v1",
            include_str!("../../tests/assets/stable-contracts/recipe_patch.v1.json"),
        ),
        (
            "scena.vocab.v1",
            include_str!("../../tests/assets/stable-contracts/vocab.v1.json"),
        ),
        (
            "scena.recipe_policy.v1",
            include_str!("../../tests/assets/stable-contracts/recipe_policy.v1.json"),
        ),
        (
            "scena.cli_error.v1",
            include_str!("../../tests/assets/stable-contracts/cli_error.v1.json"),
        ),
        (
            "scena.capability_report.v1",
            include_str!("../../tests/assets/stable-contracts/capability_report.v1.json"),
        ),
        (
            "scena.scene_inspection.v1",
            include_str!("../../tests/assets/stable-contracts/scene_inspection.v1.json"),
        ),
        (
            "scena.capture.v1",
            include_str!("../../tests/assets/stable-contracts/capture.v1.json"),
        ),
        (
            "scena.capture_baseline.v1",
            include_str!("../../tests/assets/stable-contracts/capture_baseline.v1.json"),
        ),
        (
            "scena.render_introspection.v1",
            include_str!("../../tests/assets/stable-contracts/render_introspection.v1.json"),
        ),
        (
            "scena.focus_report.v1",
            include_str!("../../tests/assets/stable-contracts/focus_report.v1.json"),
        ),
        (
            "scena.exposure_report.v1",
            include_str!("../../tests/assets/stable-contracts/exposure_report.v1.json"),
        ),
        (
            "scena.subject_observation.v1",
            include_str!("../../tests/assets/stable-contracts/subject_observation.v1.json"),
        ),
        (
            "scena.render_quality.v1",
            include_str!("../../tests/assets/stable-contracts/render_quality.v1.json"),
        ),
        (
            "scena.scene_composition.v1",
            include_str!("../../tests/assets/stable-contracts/scene_composition.v1.json"),
        ),
        (
            "scena.visibility_diagnosis.v1",
            include_str!("../../tests/assets/stable-contracts/visibility_diagnosis.v1.json"),
        ),
        (
            "scena.visual_repair_plan.v1",
            include_str!("../../tests/assets/stable-contracts/visual_repair_plan.v1.json"),
        ),
        (
            "scena.agent_loop_result.v1",
            include_str!("../../tests/assets/stable-contracts/agent_loop_result.v1.json"),
        ),
        (
            "scena.agent_smoke_template.v1",
            include_str!("../../tests/assets/stable-contracts/agent_smoke_template.v1.json"),
        ),
        (
            "scena.agent_template_catalog.v1",
            include_str!("../../tests/assets/stable-contracts/agent_template_catalog.v1.json"),
        ),
        (
            "scena.browser_proof_run.v1",
            include_str!("../../tests/assets/stable-contracts/browser_proof_run.v1.json"),
        ),
        (
            "scena.q01.required_webgpu_pixel_parity.v1",
            include_str!(
                "../../tests/assets/stable-contracts/required_webgpu_pixel_parity.v1.json"
            ),
        ),
        (
            "scena.q04.required_gpu_resource_lifecycle.v1",
            include_str!(
                "../../tests/assets/stable-contracts/required_gpu_resource_lifecycle.v1.json"
            ),
        ),
        (
            "scena.appearance_expectation.v1",
            include_str!("../../tests/assets/stable-contracts/appearance_expectation.v1.json"),
        ),
        (
            "scena.appearance_introspection.v1",
            include_str!("../../tests/assets/stable-contracts/appearance_introspection.v1.json"),
        ),
        (
            "scena.animation_introspection.v1",
            include_str!("../../tests/assets/stable-contracts/animation_introspection.v1.json"),
        ),
        (
            "scena.interaction_expectation.v1",
            include_str!("../../tests/assets/stable-contracts/interaction_expectation.v1.json"),
        ),
        (
            "scena.interaction_verification.v1",
            include_str!("../../tests/assets/stable-contracts/interaction_verification.v1.json"),
        ),
        (
            "scena.scene_host_gizmo_drag.v1",
            include_str!("../../tests/assets/stable-contracts/scene_host_gizmo_drag.v1.json"),
        ),
        (
            "scena.connector_browser.v1",
            include_str!("../../tests/assets/stable-contracts/connector_browser.v1.json"),
        ),
        (
            "scena.product_options.v1",
            include_str!("../../tests/assets/stable-contracts/product_options.v1.json"),
        ),
        (
            "scena.presentation_timeline.v1",
            include_str!("../../tests/assets/stable-contracts/presentation_timeline.v1.json"),
        ),
        (
            "scena.scene_host_grounding.v1",
            include_str!("../../tests/assets/stable-contracts/scene_host_grounding.v1.json"),
        ),
        (
            "scena.scene_recipe.v1",
            include_str!("../../tests/assets/stable-contracts/scene_recipe.v1.json"),
        ),
        (
            "scena.scene_recipe_validation.v1",
            include_str!("../../tests/assets/stable-contracts/scene_recipe_validation.v1.json"),
        ),
        (
            "scena.scene_recipe_build.v1",
            include_str!("../../tests/assets/stable-contracts/scene_recipe_build.v1.json"),
        ),
        (
            "scena.recipe_build_result.v1",
            include_str!("../../tests/assets/stable-contracts/recipe_build_result.v1.json"),
        ),
        (
            "scena.recipe_render_result.v1",
            include_str!("../../tests/assets/stable-contracts/recipe_render_result.v1.json"),
        ),
        (
            "scena.photo_render_result.v1",
            include_str!("../../tests/assets/stable-contracts/photo_render_result.v1.json"),
        ),
        (
            "scena.photo_quality_execution.v1",
            include_str!("../../tests/assets/stable-contracts/photo_quality_execution.v1.json"),
        ),
        (
            "scena.photo_plan.v1",
            include_str!("../../tests/assets/stable-contracts/photo_plan.v1.json"),
        ),
        (
            "scena.photo_candidate_plan.v1",
            include_str!("../../tests/assets/stable-contracts/photo_candidate_plan.v1.json"),
        ),
        (
            "scena.photo_shaded_candidate_selection.v1",
            include_str!(
                "../../tests/assets/stable-contracts/photo_shaded_candidate_selection.v1.json"
            ),
        ),
        (
            "scena.photo_report.v1",
            include_str!("../../tests/assets/stable-contracts/photo_report.v1.json"),
        ),
        (
            "scena.cad_inspection_result.v1",
            include_str!("../../tests/assets/stable-contracts/cad_inspection_result.v1.json"),
        ),
        (
            "scena.capture_sequence_result.v1",
            include_str!("../../tests/assets/stable-contracts/capture_sequence_result.v1.json"),
        ),
        (
            "scena.semantic_aov_result.v1",
            include_str!("../../tests/assets/stable-contracts/semantic_aov_result.v1.json"),
        ),
        (
            "scena.scene_recipe_diff.v1",
            include_str!("../../tests/assets/stable-contracts/scene_recipe_diff.v1.json"),
        ),
        (
            "scena.scene_recipe_diff_result.v1",
            include_str!("../../tests/assets/stable-contracts/scene_recipe_diff_result.v1.json"),
        ),
        (
            "scena.placement_result.v1",
            include_str!("../../tests/assets/stable-contracts/placement_result.v1.json"),
        ),
        (
            "scena.annotation_projection.v1",
            include_str!("../../tests/assets/stable-contracts/annotation_projection.v1.json"),
        ),
        (
            "scena.asset_geometry_summary.v1",
            include_str!("../../tests/assets/stable-contracts/asset_geometry_summary.v1.json"),
        ),
        (
            "scena.asset_load_report.v1",
            include_str!("../../tests/assets/stable-contracts/asset_load_report.v1.json"),
        ),
        (
            "scena.asset_doctor.v1",
            include_str!("../../tests/assets/stable-contracts/asset_doctor.v1.json"),
        ),
        (
            "scena.asset_conversion.v1",
            include_str!("../../tests/assets/stable-contracts/asset_conversion.v1.json"),
        ),
        (
            "scena.asset_catalog.v1",
            include_str!("../../tests/assets/stable-contracts/asset_catalog.v1.json"),
        ),
        (
            "scena.asset_readiness_report.v1",
            include_str!("../../tests/assets/stable-contracts/asset_readiness_report.v1.json"),
        ),
        (
            "scena.scene_host_asset_import.v1",
            include_str!("../../tests/assets/stable-contracts/scene_host_asset_import.v1.json"),
        ),
        (
            "scena.subtree.v1",
            include_str!("../../tests/assets/stable-contracts/scene_host_subtree.v1.json"),
        ),
        (
            "scena.scene_host_measurement_overlay.v1",
            include_str!(
                "../../tests/assets/stable-contracts/scene_host_measurement_overlay.v1.json"
            ),
        ),
        (
            "scena.scene_host_section_box.v1",
            include_str!("../../tests/assets/stable-contracts/scene_host_section_box.v1.json"),
        ),
        (
            "scena.scene_host_clipping_planes.v1",
            include_str!("../../tests/assets/stable-contracts/scene_host_clipping_planes.v1.json"),
        ),
        (
            "scena.scene_host_visual_state.v1",
            include_str!("../../tests/assets/stable-contracts/scene_host_visual_state.v1.json"),
        ),
        (
            "scena.scene_host_visual_states.v1",
            include_str!("../../tests/assets/stable-contracts/scene_host_visual_states.v1.json"),
        ),
        (
            "scena.animation_inventory.v1",
            include_str!(
                "../../tests/assets/stable-contracts/scene_host_animation_inventory.v1.json"
            ),
        ),
        (
            "scena.visual_patch.v1",
            include_str!("../../tests/assets/stable-contracts/visual_patch.v1.json"),
        ),
        (
            "scena.host_event.v1",
            include_str!("../../tests/assets/stable-contracts/host_event.v1.json"),
        ),
    ]
}
