use crate::app::prelude::*;

pub(crate) fn check_m3a_import_runtime_contracts(root: &Path, findings: &mut Vec<Finding>) {
    require_contains(
        root,
        findings,
        "ARCH-M3A-SCENE-IMPORT",
        "src/scene/import/load.rs",
        &[
            "pub async fn import<",
            "pub async fn import_with<",
            "pub fn replace_import(",
            "mark_stale",
        ],
    );
    require_contains(
        root,
        findings,
        "ARCH-M3A-SCENE-IMPORT",
        "src/scene/import.rs",
        &[
            "pub struct ImportOptions",
            "pub enum SourceUnits",
            "pub enum SourceCoordinateSystem",
            "Centimeters",
            "Inches",
            "Feet",
            "ZUpRightHanded",
            "pub struct SceneImport",
            "pub struct ImportAnchor",
            "pub struct ImportConnector",
            "pub struct ImportClip",
            "pub struct ImportPivot",
            "pub fn instantiate(",
            "pub fn instantiate_with(",
            "node_bounds",
            "source_node.meshes()",
            "scene_asset: &SceneAsset",
            "InvalidAnchorExtras",
            "convert_marker_units(",
            "placement_node",
            "placement_transform",
            "root_from_node",
            "convert_transform(source_node.transform())",
            "ImportDiagnosticOverlayKind::Origin",
            "ImportDiagnosticOverlayKind::Axes",
            "ImportDiagnosticOverlayKind::Bounds",
            "ImportDiagnosticOverlayKind::Anchor",
            "ImportDiagnosticOverlayKind::Connector",
            "ImportDiagnosticOverlayKind::Pivot",
        ],
    );
    require_contains(
        root,
        findings,
        "ARCH-M3A-SCENE-IMPORT",
        "src/scene/import/handedness.rs",
        &[
            "reject_unproven_left_handed_mesh_import",
            "has_negative_determinant",
            "UnsupportedCoordinateSystem",
            "left-handed mesh imports require explicit winding and normal correction proof",
        ],
    );
    require_contains(
        root,
        findings,
        "ARCH-M3A-SCENE-IMPORT",
        "src/scene/import/types.rs",
        &["ImportBuild", "NodeKind::Mesh", "mesh_node_kind"],
    );
    require_contains(
        root,
        findings,
        "ARCH-M3A-SCENE-IMPORT",
        "src/scene/import/options.rs",
        &[
            "pub const fn gltf_default() -> Self",
            "pub const fn with_source_units",
            "pub const fn with_source_coordinate_system",
            "pub(super) fn convert_transform",
            "convert_connector_transform(transform)",
            "AnimationTarget::Translation",
            "AnimationTarget::Rotation",
            "AnimationTarget::Scale",
            "AnimationTarget::Weights",
        ],
    );
    require_contains(
        root,
        findings,
        "ARCH-M3A-SCENE-IMPORT",
        "src/scene/import/accessors.rs",
        &[
            "pub const fn placement_node",
            "self.placement_transform",
            "pub fn channels(&self)",
            "pub const fn duration_seconds",
        ],
    );
    require_contains(
        root,
        findings,
        "ARCH-M3A-SCENE-IMPORT",
        "src/scene/import/lookups.rs",
        &[
            "LookupError::StaleImport",
            "pub fn node(&self, name: &str)",
            "pub fn first_node(&self, name: &str)",
            "pub fn nodes_named",
            "pub fn path(&self, path: &str)",
            "pub fn bounds_local",
            "pub fn bounds_world",
            "scene.world_transform(record.node)",
            "pub fn pivot(&self",
            "pub fn diagnostic_overlays",
            "pub fn anchor(&self",
            "pub fn replacement_anchor",
            "pub fn connector(&self",
            "pub fn replacement_connector",
            "pub fn connectors_named",
            "pub fn first_anchor",
            "pub fn anchors_named",
            "pub fn clip(&self",
            "pub fn first_clip",
            "pub fn clips_named",
            "AmbiguousAnchorName",
            "AmbiguousClipName",
            "fn path_segments(path: &str)",
        ],
    );
}
