pub(super) const FIXTURES: &[(&str, &str)] = &[
    (
        "tests/assets/stable-contracts/capability_report.v1.json",
        "scena.capability_report.v1",
    ),
    (
        "tests/assets/stable-contracts/schema_catalog.v1.json",
        "scena.schema_catalog.v1",
    ),
    (
        "tests/assets/stable-contracts/schema_entry.v1.json",
        "scena.schema_entry.v1",
    ),
    (
        "tests/assets/stable-contracts/scene_inspection.v1.json",
        "scena.scene_inspection.v1",
    ),
    (
        "tests/assets/stable-contracts/capture.v1.json",
        "scena.capture.v1",
    ),
    (
        "tests/assets/stable-contracts/capture_baseline.v1.json",
        "scena.capture_baseline.v1",
    ),
    (
        "tests/assets/stable-contracts/render_introspection.v1.json",
        "scena.render_introspection.v1",
    ),
    (
        "tests/assets/stable-contracts/visibility_diagnosis.v1.json",
        "scena.visibility_diagnosis.v1",
    ),
    (
        "tests/assets/stable-contracts/visual_repair_plan.v1.json",
        "scena.visual_repair_plan.v1",
    ),
    (
        "tests/assets/stable-contracts/agent_loop_result.v1.json",
        "scena.agent_loop_result.v1",
    ),
    (
        "tests/assets/stable-contracts/agent_smoke_template.v1.json",
        "scena.agent_smoke_template.v1",
    ),
    (
        "tests/assets/stable-contracts/appearance_expectation.v1.json",
        "scena.appearance_expectation.v1",
    ),
    (
        "tests/assets/stable-contracts/appearance_introspection.v1.json",
        "scena.appearance_introspection.v1",
    ),
    (
        "tests/assets/stable-contracts/animation_introspection.v1.json",
        "scena.animation_introspection.v1",
    ),
    (
        "tests/assets/stable-contracts/interaction_expectation.v1.json",
        "scena.interaction_expectation.v1",
    ),
    (
        "tests/assets/stable-contracts/interaction_verification.v1.json",
        "scena.interaction_verification.v1",
    ),
    (
        "tests/assets/stable-contracts/scene_host_gizmo_drag.v1.json",
        "scena.scene_host_gizmo_drag.v1",
    ),
    (
        "tests/assets/stable-contracts/scene_recipe.v1.json",
        "scena.scene_recipe.v1",
    ),
    (
        "tests/assets/stable-contracts/scene_recipe_validation.v1.json",
        "scena.scene_recipe_validation.v1",
    ),
    (
        "tests/assets/stable-contracts/placement_result.v1.json",
        "scena.placement_result.v1",
    ),
    (
        "tests/assets/stable-contracts/annotation_projection.v1.json",
        "scena.annotation_projection.v1",
    ),
    (
        "tests/assets/stable-contracts/asset_geometry_summary.v1.json",
        "scena.asset_geometry_summary.v1",
    ),
    (
        "tests/assets/stable-contracts/asset_load_report.v1.json",
        "scena.asset_load_report.v1",
    ),
    (
        "tests/assets/stable-contracts/asset_doctor.v1.json",
        "scena.asset_doctor.v1",
    ),
    (
        "tests/assets/stable-contracts/asset_catalog.v1.json",
        "scena.asset_catalog.v1",
    ),
    (
        "tests/assets/stable-contracts/asset_readiness_report.v1.json",
        "scena.asset_readiness_report.v1",
    ),
    (
        "tests/assets/stable-contracts/connector_browser.v1.json",
        "scena.connector_browser.v1",
    ),
    (
        "tests/assets/stable-contracts/product_options.v1.json",
        "scena.product_options.v1",
    ),
    (
        "tests/assets/stable-contracts/presentation_timeline.v1.json",
        "scena.presentation_timeline.v1",
    ),
    (
        "tests/assets/stable-contracts/scene_host_grounding.v1.json",
        "scena.scene_host_grounding.v1",
    ),
    (
        "tests/assets/stable-contracts/scene_host_asset_import.v1.json",
        "scena.scene_host_asset_import.v1",
    ),
    (
        "tests/assets/stable-contracts/scene_host_subtree.v1.json",
        "scena.subtree.v1",
    ),
    (
        "tests/assets/stable-contracts/scene_host_animation_inventory.v1.json",
        "scena.animation_inventory.v1",
    ),
    (
        "tests/assets/stable-contracts/scene_host_measurement_overlay.v1.json",
        "scena.scene_host_measurement_overlay.v1",
    ),
    (
        "tests/assets/stable-contracts/scene_host_section_box.v1.json",
        "scena.scene_host_section_box.v1",
    ),
    (
        "tests/assets/stable-contracts/scene_host_visual_state.v1.json",
        "scena.scene_host_visual_state.v1",
    ),
    (
        "tests/assets/stable-contracts/scene_host_visual_states.v1.json",
        "scena.scene_host_visual_states.v1",
    ),
    (
        "tests/assets/stable-contracts/visual_patch.v1.json",
        "scena.visual_patch.v1",
    ),
    (
        "tests/assets/stable-contracts/visual_patch_result.v1.json",
        "scena.visual_patch.v1",
    ),
    (
        "tests/assets/stable-contracts/host_event.v1.json",
        "scena.host_event.v1",
    ),
];

pub(super) const REQUIRED_FILES: &[&str] = &[
    "examples/scene_host_contracts.rs",
    "examples/scene_host_browser_contracts.js",
    "tests/assets/stable-contracts/asset_provenance.json",
    "docs/checklists/scene-host-browser-gpu-proof.md",
];
