use crate::app::prelude::*;

pub(super) fn check_scena_viewer_element(root: &Path, findings: &mut Vec<Finding>) {
    require_contains(
        root,
        findings,
        "SCENA-VIEWER-ELEMENT",
        "Cargo.toml",
        &[
            "viewer-element = []",
            "browser-probe = [\"viewer-element\"]",
        ],
    );
    require_contains(
        root,
        findings,
        "SCENA-VIEWER-ELEMENT",
        "src/lib.rs",
        &[
            "pub mod viewer_element;",
            "SCENA_VIEWER_TAG",
            "ScenaViewerAccessibilityDefaults",
            "ScenaViewerAnnotationAnchor",
            "ScenaViewerAnnotationError",
            "ScenaViewerAttributes",
            "ScenaViewerDropDecision",
            "ScenaViewerDropKind",
            "ScenaViewerDroppedFile",
            "ScenaViewerInspectorDiagnostic",
            "ScenaViewerInspectorSnapshot",
            "ScenaViewerKeyboardAction",
            "ScenaViewerProgress",
            "ScenaViewerProgressPhase",
            "ScenaViewerVariantOption",
            "ScenaViewerVariantSelection",
            "define_scena_viewer",
        ],
    );
    require_contains(
        root,
        findings,
        "SCENA-VIEWER-ELEMENT",
        "src/viewer_element.rs",
        &[
            "mod annotations;",
            "mod model;",
            "mod inspector;",
            "pub use annotations::",
            "pub use model::",
            "pub use inspector::",
            "pub const SCENA_VIEWER_TAG",
            "defineScenaViewerElement",
            "customElements.define",
            "attachShadow",
            "observedAttributes",
            "scena-viewer-ready",
            "setLoadProgress",
            "progress.part = \"progress\"",
            "progressbar",
            "scena-viewer-progress",
            "scena-viewer-progress-rendered",
            "dragover",
            "drop",
            "_handleDrop",
            "_isSupportedAssetFile",
            "scena-viewer-file-drop",
            "scena-viewer-drop-error",
            "setMaterialVariants",
            "variantPicker.part = \"variant-picker\"",
            "scena-viewer-variant-change",
            "scena-viewer-variants-ready",
            "tabIndex = 0",
            "aria-roledescription",
            "_handleKeydown",
            "_keyboardAction",
            "scena-viewer-key-control",
            "setInspectorSnapshot",
            "setInspectorDiagnostics",
            "clearInspectorSnapshot",
            "inspector.part = \"inspector\"",
            "inspector-status",
            "inspector-list",
            "scena-viewer-inspector-rendered",
            "annotationSlot.name = \"annotation\"",
            "annotationAnchors",
            "requestAnnotationProjections",
            "setAnnotationProjections",
            "data-position",
            "data-normal",
            "data-surface",
            "scena-viewer-annotations-request",
            "scena-viewer-annotations-rendered",
        ],
    );
    require_contains(
        root,
        findings,
        "SCENA-VIEWER-ELEMENT",
        "src/viewer_element/annotations.rs",
        &[
            "pub struct ScenaViewerAnnotationAnchor",
            "pub enum ScenaViewerAnnotationError",
            "from_attributes",
            "data-position",
            "data-normal",
            "data-surface",
            "MissingPosition",
            "InvalidVector",
        ],
    );
    require_contains(
        root,
        findings,
        "SCENA-VIEWER-ELEMENT",
        "src/viewer_element/model.rs",
        &[
            "pub struct ScenaViewerAccessibilityDefaults",
            "host_role",
            "host_label",
            "canvas_label",
            "touch_action",
            "host_is_keyboard_focusable",
            "pub enum ScenaViewerKeyboardAction",
            "from_key",
            "event_action",
            "pub struct ScenaViewerAttributes",
            "from_pairs",
            "pub enum ScenaViewerDropKind",
            "pub struct ScenaViewerDroppedFile",
            "pub struct ScenaViewerDropDecision",
            "from_file_names",
            "status_text",
            "pub enum ScenaViewerProgressPhase",
            "pub struct ScenaViewerProgress",
            "from_asset_event",
            "aria_text",
            "pub struct ScenaViewerVariantOption",
            "pub struct ScenaViewerVariantSelection",
            "with_active",
        ],
    );
    require_contains(
        root,
        findings,
        "SCENA-VIEWER-ELEMENT",
        "src/viewer_element/inspector.rs",
        &[
            "pub struct ScenaViewerInspectorSnapshot",
            "from_renderer_state",
            "status_text",
            "warning_count",
            "error_count",
            "pub struct ScenaViewerInspectorDiagnostic",
            "DiagnosticSeverity",
            "RendererStats",
        ],
    );
    require_contains(
        root,
        findings,
        "SCENA-VIEWER-ELEMENT",
        "tests/scena_viewer_element.rs",
        &[
            "scena_viewer_attributes_parse_model_viewer_style_surface",
            "scena_viewer_attributes_default_to_safe_drop_in_viewer_values",
            "scena_viewer_progress_maps_asset_events_to_accessible_details",
            "scena_viewer_drop_decision_accepts_gltf_and_reports_rejections",
            "scena_viewer_variant_selection_tracks_available_and_active_names",
            "scena_viewer_accessibility_defaults_define_mobile_and_keyboard_surface",
            "scena_viewer_inspector_snapshot_summarizes_diagnostics_and_render_state",
            "scena_viewer_annotation_anchor_parses_dataset_position_normal_and_surface",
            "camera-controls",
            "tone-mapping",
        ],
    );
    require_contains(
        root,
        findings,
        "SCENA-VIEWER-ELEMENT",
        "tests/browser/m6_rust_wasm_renderer_probe.js",
        &[
            "assertScenaViewerElementProof",
            "runScenaViewerElementProof",
            "scena-viewer-element-browser-proof.png",
            "SCENA_BROWSER_VIEWER_ELEMENT_ONLY",
            "scena.scena_viewer_element_browser_proof.v1",
            "progress_sequence",
            "annotation_tracking_sequence",
            "annotation_update_visible",
            "inspector_fixture_schema",
            "scena.scena_viewer_inspector_snapshot.v1",
        ],
    );
    require_contains(
        root,
        findings,
        "SCENA-VIEWER-ELEMENT",
        "tests/browser/m6_rust_wasm_renderer_probe_page.js",
        &[
            "defineScenaViewer",
            "scenaViewerElementProbe",
            "scena.scena_viewer_element_browser_proof.v1",
            "loadInspectorSnapshot",
            "/fixtures/viewer/inspector_snapshot.json",
            "scena.scena_viewer_inspector_snapshot.v1",
            "scena-viewer-progress-rendered",
            "progress_sequence",
            "scena-viewer-file-drop",
            "scena-viewer-drop-error",
            "scena-viewer-variant-change",
            "scena-viewer-annotations-rendered",
            "annotation_tracking_sequence",
            "annotation_update_visible",
            "scena-viewer-inspector-rendered",
            "scena-viewer-key-control",
        ],
    );
    require_contains(
        root,
        findings,
        "SCENA-VIEWER-ELEMENT",
        "docs/browser.md",
        &[
            "<scena-viewer",
            "defineScenaViewer",
            "viewer-element",
            "shadow DOM",
            "canvas",
            "progressbar",
            "scena-viewer-progress",
            "drag-and-drop",
            "scena-viewer-file-drop",
            "scena-viewer-drop-error",
            "material variant picker",
            "scena-viewer-variant-change",
            "mobile",
            "accessibility",
            "keyboard",
            "scena-viewer-key-control",
            "inspector/dev overlay",
            "setInspectorSnapshot",
            "scena-viewer-inspector-rendered",
            "annotation overlay",
            "data-position",
            "scena-viewer-annotations-request",
            "scena-viewer-annotations-rendered",
            "SCENA_BROWSER_VIEWER_ELEMENT_ONLY=1",
            "scena-viewer-element-browser-proof.png",
        ],
    );
    require_contains(
        root,
        findings,
        "SCENA-VIEWER-ELEMENT",
        "tests/assets/viewer/inspector_snapshot.json",
        &[
            "scena.scena_viewer_inspector_snapshot.v1",
            "scena-viewer-inspector-fixture",
            "\"overlay\": \"Diagnostics\"",
            "\"diagnostics\"",
            "\"stats\"",
            "\"FrameBounds\"",
        ],
    );
    require_contains(
        root,
        findings,
        "SCENA-VIEWER-ELEMENT",
        "docs/checklists/next-release-easy-use-and-state-of-the-art.md",
        &[
            "custom-element\nfoundation and browser UI proof **[shipped]**",
            "src/viewer_element.rs",
            "SCENA-VIEWER-ELEMENT",
            "ScenaViewerProgress",
            "scena-viewer-progress-rendered",
            "loading progress sequence proof **[shipped]**",
            "ScenaViewerDropDecision",
            "scena-viewer-file-drop",
            "ScenaViewerVariantSelection",
            "scena-viewer-variant-change",
            "ScenaViewerAccessibilityDefaults",
            "scena-viewer-key-control",
            "ScenaViewerInspectorSnapshot",
            "scena-viewer-inspector-rendered",
            "scena.scena_viewer_inspector_snapshot.v1",
            "ScenaViewerAnnotationAnchor",
            "scena-viewer-annotations-rendered",
            "annotation tracking proof **[shipped]**",
            "scena.scena_viewer_element_browser_proof.v1",
            "scena-viewer-element-browser-proof.png",
            "Full\n  asset loading/rendering parity remains open under bet 1.1",
        ],
    );
}
