use crate::app::prelude::*;

pub(super) fn check_scena_viewer_element(root: &Path, findings: &mut Vec<Finding>) {
    require_contains(
        root,
        findings,
        "SCENA-VIEWER-ELEMENT",
        "Cargo.toml",
        &["viewer-element = []"],
    );
    require_contains(
        root,
        findings,
        "SCENA-VIEWER-ELEMENT",
        "src/lib.rs",
        &[
            "pub mod viewer_element;",
            "SCENA_VIEWER_TAG",
            "ScenaViewerAttributes",
            "ScenaViewerDropDecision",
            "ScenaViewerDropKind",
            "ScenaViewerDroppedFile",
            "ScenaViewerProgress",
            "ScenaViewerProgressPhase",
            "define_scena_viewer",
        ],
    );
    require_contains(
        root,
        findings,
        "SCENA-VIEWER-ELEMENT",
        "src/viewer_element.rs",
        &[
            "pub const SCENA_VIEWER_TAG",
            "pub struct ScenaViewerAttributes",
            "from_pairs",
            "pub enum ScenaViewerDropKind",
            "pub struct ScenaViewerDroppedFile",
            "pub struct ScenaViewerDropDecision",
            "from_file_names",
            "status_text",
            "pub enum ScenaViewerProgressPhase",
            "pub struct ScenaViewerProgress",
            "from_asset_event",
            "aria_text",
            "defineScenaViewerElement",
            "customElements.define",
            "attachShadow",
            "observedAttributes",
            "scena-viewer-ready",
            "setLoadProgress",
            "progress.part = \"progress\"",
            "progressbar",
            "scena-viewer-progress",
            "scena-viewer-progress-rendered",
            "dragover",
            "drop",
            "_handleDrop",
            "_isSupportedAssetFile",
            "scena-viewer-file-drop",
            "scena-viewer-drop-error",
        ],
    );
    require_contains(
        root,
        findings,
        "SCENA-VIEWER-ELEMENT",
        "tests/scena_viewer_element.rs",
        &[
            "scena_viewer_attributes_parse_model_viewer_style_surface",
            "scena_viewer_attributes_default_to_safe_drop_in_viewer_values",
            "scena_viewer_progress_maps_asset_events_to_accessible_details",
            "scena_viewer_drop_decision_accepts_gltf_and_reports_rejections",
            "camera-controls",
            "tone-mapping",
        ],
    );
    require_contains(
        root,
        findings,
        "SCENA-VIEWER-ELEMENT",
        "docs/browser.md",
        &[
            "<scena-viewer",
            "defineScenaViewer",
            "viewer-element",
            "shadow DOM",
            "canvas",
            "progressbar",
            "scena-viewer-progress",
            "drag-and-drop",
            "scena-viewer-file-drop",
            "scena-viewer-drop-error",
        ],
    );
    require_contains(
        root,
        findings,
        "SCENA-VIEWER-ELEMENT",
        "docs/checklists/next-release-easy-use-and-state-of-the-art.md",
        &[
            "custom-element\nfoundation **[shipped]**",
            "src/viewer_element.rs",
            "SCENA-VIEWER-ELEMENT",
            "ScenaViewerProgress",
            "scena-viewer-progress-rendered",
            "ScenaViewerDropDecision",
            "scena-viewer-file-drop",
            "Full\n  asset loading/rendering parity remains open under bet 1.1",
        ],
    );
}
