use super::{
    CatalogSeed, PhotographicSurfaceKind, fabric, fabric_scanned, leather, leather_approximated,
    leather_scanned, metal, plastic, rubber,
};

pub(super) const CATALOG: &[CatalogSeed] = &[
    metal(
        "Metal049A",
        "Clean smooth silver metal",
        PhotographicSurfaceKind::PolishedMetal,
        &["clean", "silver", "smooth"],
    ),
    metal(
        "Metal049B",
        "Clean smeared silver metal",
        PhotographicSurfaceKind::SatinMetal,
        &["clean", "silver", "smeared", "smooth"],
    ),
    metal(
        "Metal050A",
        "Clean polished aluminium",
        PhotographicSurfaceKind::PolishedMetal,
        &["aluminium", "clean", "polished", "smooth"],
    ),
    metal(
        "Metal052A",
        "Smooth iron",
        PhotographicSurfaceKind::SatinMetal,
        &["iron", "smooth"],
    ),
    metal(
        "Metal057A",
        "Clean smooth copper",
        PhotographicSurfaceKind::PolishedMetal,
        &["clean", "copper", "smooth"],
    ),
    metal(
        "Metal048A",
        "Clean smooth gold metal",
        PhotographicSurfaceKind::PolishedMetal,
        &["clean", "gold", "smooth"],
    ),
    metal(
        "Metal041A",
        "Clean iron",
        PhotographicSurfaceKind::SatinMetal,
        &["clean", "iron"],
    ),
    metal(
        "Metal046A",
        "Clean dark metal",
        PhotographicSurfaceKind::SatinMetal,
        &["black", "clean", "dark"],
    ),
    metal(
        "Metal030",
        "Smooth grey metal",
        PhotographicSurfaceKind::SatinMetal,
        &["grey", "smooth"],
    ),
    metal(
        "Metal032",
        "Fine smooth grey metal",
        PhotographicSurfaceKind::SatinMetal,
        &["grey", "smooth"],
    ),
    metal(
        "Metal036",
        "Neutral smooth metal",
        PhotographicSurfaceKind::SatinMetal,
        &["grey", "smooth"],
    ),
    metal(
        "Metal035",
        "Smooth copper",
        PhotographicSurfaceKind::PolishedMetal,
        &["copper", "orange", "smooth"],
    ),
    metal(
        "Metal027",
        "Black powder-coated steel fine",
        PhotographicSurfaceKind::PowderCoatedMetal,
        &["black", "painted", "powder", "steel"],
    ),
    metal(
        "Metal028",
        "Black powder-coated steel medium",
        PhotographicSurfaceKind::PowderCoatedMetal,
        &["black", "painted", "powder", "steel"],
    ),
    metal(
        "Metal029",
        "Black powder-coated steel coarse",
        PhotographicSurfaceKind::PowderCoatedMetal,
        &["black", "painted", "powder", "steel"],
    ),
    metal(
        "Metal009",
        "Brushed silver steel fine",
        PhotographicSurfaceKind::BrushedMetal,
        &["brushed", "silver", "steel"],
    ),
    metal(
        "Metal011",
        "Brushed silver steel medium",
        PhotographicSurfaceKind::BrushedMetal,
        &["brushed", "silver", "steel"],
    ),
    metal(
        "Metal012",
        "Brushed silver steel coarse",
        PhotographicSurfaceKind::BrushedMetal,
        &["brushed", "silver", "steel"],
    ),
    plastic(
        "Plastic013A",
        "Clean white molded plastic",
        &["clean", "white"],
    ),
    plastic("Plastic010", "Smooth white plastic", &["smooth", "white"]),
    plastic(
        "Plastic006",
        "Shiny black plastic",
        &["black", "shiny", "smooth"],
    ),
    plastic("Plastic012A", "Clean black plastic", &["black", "clean"]),
    plastic("Plastic015A", "Clean blue plastic", &["blue", "clean"]),
    plastic("Plastic017A", "Clean green plastic", &["clean", "green"]),
    plastic("Plastic011", "Smooth grey plastic", &["grey", "smooth"]),
    plastic("Plastic008", "Smooth blue plastic", &["blue", "smooth"]),
    plastic("Plastic016A", "Clean yellow plastic", &["clean", "yellow"]),
    plastic(
        "Plastic014A",
        "Clean red-orange plastic",
        &["clean", "orange", "red"],
    ),
    plastic("Plastic018A", "Clean grey plastic", &["clean", "grey"]),
    plastic("Plastic007", "Smooth red plastic", &["red", "smooth"]),
    fabric(
        "Fabric061",
        "Neutral rough upholstery fabric",
        &["neutral", "rough"],
    ),
    fabric(
        "Fabric066",
        "Dense neutral upholstery fabric",
        &["dense", "neutral"],
    ),
    fabric_scanned(
        "Fabric083",
        "Fine grey check fabric",
        &["check", "clean", "grey", "woven"],
    ),
    fabric(
        "Fabric036",
        "Clean smooth woven fabric",
        &["clean", "smooth", "woven"],
    ),
    fabric(
        "Fabric082A",
        "Fine grey woven fabric",
        &["fine", "grey", "woven"],
    ),
    fabric(
        "Fabric081A",
        "Fine blue woven fabric",
        &["blue", "fine", "woven"],
    ),
    fabric(
        "Fabric039",
        "Clean neutral weave",
        &["clean", "smooth", "woven"],
    ),
    fabric("Fabric035", "Clean fine weave", &["clean", "fine", "woven"]),
    fabric_scanned(
        "Fabric068",
        "Orange wool fabric",
        &["orange", "wool", "woven"],
    ),
    fabric_scanned(
        "Fabric069",
        "Blue denim fabric",
        &["blue", "denim", "jeans"],
    ),
    fabric_scanned(
        "Fabric070",
        "Light green sportswear fabric",
        &["green", "light", "sportswear"],
    ),
    fabric_scanned(
        "Fabric071",
        "Blue-white striped fabric",
        &["blue", "striped", "white"],
    ),
    fabric_scanned(
        "Fabric072",
        "Dark blue striped fabric",
        &["blue", "dark", "striped"],
    ),
    fabric_scanned(
        "Fabric073",
        "Fine blue stripe fabric",
        &["blue", "fine", "striped"],
    ),
    fabric_scanned("Fabric074", "Solid blue woven fabric", &["blue", "woven"]),
    fabric_scanned(
        "Fabric075",
        "Dark blue-grey woven fabric",
        &["blue", "dark", "grey", "woven"],
    ),
    fabric_scanned(
        "Fabric076",
        "Blue-white woven fabric",
        &["blue", "white", "woven"],
    ),
    fabric_scanned(
        "Fabric077",
        "White denim fabric",
        &["denim", "jeans", "white"],
    ),
    fabric_scanned(
        "Fabric078",
        "Green woven cloth",
        &["cloth", "green", "woven"],
    ),
    fabric_scanned(
        "Fabric079",
        "Black-grey striped fabric",
        &["black", "grey", "striped", "white"],
    ),
    fabric_scanned(
        "Fabric080",
        "Red plaid cotton fabric",
        &["clean", "cotton", "plaid", "red"],
    ),
    leather("Leather001", "Smooth brown leather", &["brown", "smooth"]),
    leather("Leather004", "Smooth white leather", &["smooth", "white"]),
    leather("Leather005", "Smooth red leather", &["red", "smooth"]),
    leather_approximated(
        "Leather008",
        "Black embossed leather",
        &["black", "dark", "embossed"],
    ),
    leather(
        "Leather009",
        "Black upholstery leather",
        &["black", "sofa", "upholstery"],
    ),
    leather(
        "Leather010",
        "Brown upholstery leather",
        &["brown", "sofa", "upholstery"],
    ),
    leather_approximated(
        "Leather014",
        "Worn brown leather",
        &["brown", "scratched", "used", "vintage"],
    ),
    leather(
        "Leather015",
        "Dark perforated leather",
        &["brown", "dark", "perforated"],
    ),
    leather(
        "Leather016",
        "Beige perforated leather",
        &["beige", "perforated", "smooth"],
    ),
    leather(
        "Leather024",
        "Glossy red leather",
        &["red", "shiny", "smooth"],
    ),
    leather("Leather031", "Clean black leather", &["black", "clean"]),
    leather(
        "Leather032",
        "Scratched black leather",
        &["black", "scratched", "used"],
    ),
    leather_scanned(
        "Leather037",
        "Clean dark brown leather",
        &["brown", "clean", "dark"],
    ),
    leather_scanned(
        "Leather038",
        "Fine smooth brown leather",
        &["brown", "fine", "smooth"],
    ),
    leather("Leather030", "Dark brown leather", &["brown", "dark"]),
    leather("Leather026", "Smooth black leather", &["black", "smooth"]),
    leather(
        "Leather027",
        "Fine black leather",
        &["black", "fine", "smooth"],
    ),
    leather_scanned(
        "Leather039",
        "Light suede leather",
        &["light", "rough", "suede"],
    ),
    rubber("Rubber001", "Fine black rubber", &["black", "fine"]),
    rubber("Rubber002", "Medium black rubber", &["black", "medium"]),
    rubber("Rubber003", "Coarse black rubber", &["black", "coarse"]),
    rubber("Rubber004", "Heavy black rubber", &["black", "heavy"]),
];
