use crate::app::prelude::*;

pub(super) fn check_clearcoat_material_contracts(root: &Path, findings: &mut Vec<Finding>) {
    require_contains(
        root,
        findings,
        "ASSETS-M8",
        "src/assets/gltf/materials.rs",
        &[
            "clearcoatTexture",
            "clearcoatRoughnessTexture",
            "clearcoatNormalTexture",
            "with_clearcoat_texture",
            "with_clearcoat_roughness_texture",
            "with_clearcoat_normal_texture",
            "with_clearcoat_normal_scale",
        ],
    );
    require_contains(
        root,
        findings,
        "ASSETS-M8",
        "src/material.rs",
        &[
            "with_clearcoat_texture",
            "with_clearcoat_roughness_texture",
            "with_clearcoat_normal_texture",
            "clearcoat_normal_scale",
        ],
    );
    require_contains(
        root,
        findings,
        "ASSETS-M8",
        "src/render/prepare/materials.rs",
        &[
            "clearcoat_texture_sample",
            "clearcoat_roughness_texture_sample",
            "clearcoat_normal_texture_sample",
        ],
    );
    require_contains(
        root,
        findings,
        "ASSETS-M8",
        "tests/m8_assets_materials_ecosystem.rs",
        &[
            "m8_clearcoat_material_factors_are_parsed_from_gltf",
            "m8_clearcoat_texture_slots_are_parsed_from_gltf",
            "m8_clearcoat_png_textures_affect_cpu_preview_pixels",
            "m8_clearcoat_normal_texture_affects_cpu_preview_pixels",
            "clearcoat_texture",
            "clearcoat_roughness_texture",
            "clearcoat_normal_texture",
        ],
    );
}
