use crate::app::prelude::*;

pub(super) fn check_iridescence_material_contracts(root: &Path, findings: &mut Vec<Finding>) {
    require_contains(
        root,
        findings,
        "ASSETS-M8",
        "src/assets/gltf/material_extensions.rs",
        &[
            "KHR_materials_iridescence",
            "iridescenceFactor",
            "iridescenceIor",
            "iridescenceThicknessMinimum",
            "iridescenceThicknessMaximum",
            "iridescenceTexture",
            "iridescenceThicknessTexture",
        ],
    );
    require_contains(
        root,
        findings,
        "ASSETS-M8",
        "src/assets/gltf/materials.rs",
        &[
            "with_iridescence_factor",
            "with_iridescence_ior",
            "with_iridescence_thickness_range_nm",
            "with_iridescence_texture",
            "with_iridescence_thickness_texture",
            "TextureColorSpace::Linear",
        ],
    );
    require_contains(
        root,
        findings,
        "ASSETS-M8",
        "src/material/extensions.rs",
        &[
            "with_iridescence_factor",
            "with_iridescence_ior",
            "with_iridescence_thickness_range_nm",
            "with_iridescence_texture",
            "with_iridescence_thickness_texture",
            "iridescence_factor",
            "iridescence_ior",
            "iridescence_thickness_minimum_nm",
            "iridescence_thickness_maximum_nm",
        ],
    );
    require_contains(
        root,
        findings,
        "ASSETS-M8",
        "src/render/prepare/materials.rs",
        &[
            "iridescence_texture_sample",
            "iridescence_thickness_texture_sample",
        ],
    );
    require_contains(
        root,
        findings,
        "ASSETS-M8",
        "src/render/prepare/pbr_contract.rs",
        &[
            "iridescence_light_contribution",
            "iridescence_light_contribution_uses_factor_thickness_and_textures",
        ],
    );
    require_contains(
        root,
        findings,
        "ASSETS-M8",
        "tests/m8_assets_materials_ecosystem.rs",
        &[
            "m8_iridescence_material_factors_are_parsed_from_gltf",
            "m8_iridescence_texture_slots_are_parsed_from_gltf",
            "m8_iridescence_png_textures_affect_cpu_preview_pixels",
            "iridescence_texture",
            "iridescence_thickness_texture",
        ],
    );
    require_contains(
        root,
        findings,
        "ASSETS-M8",
        "src/render/prepare/resources.rs",
        &[
            "iridescence",
            "iridescence_thickness",
            "backend_material_slots_preserve_all_texture_roles_and_material_only_slots",
        ],
    );
    require_contains(
        root,
        findings,
        "ASSETS-M8",
        "src/render/prepare/material_batch.rs",
        &[
            "MaterialTextureRole::Iridescence",
            "MaterialTextureRole::IridescenceThickness",
            "iridescence_sampler_mismatch_blocks_batching_with_diagnostic_role",
            "iridescence_thickness_sampler_mismatch_blocks_batching_with_diagnostic_role",
        ],
    );
    require_contains(
        root,
        findings,
        "ASSETS-M8",
        "src/render/gpu/material_uniform.rs",
        &[
            "MATERIAL_UNIFORM_BYTE_LEN: u64 = 192",
            "iridescence_factors",
            "material.iridescence_factor()",
            "material.iridescence_ior()",
            "material.iridescence_thickness_minimum_nm()",
            "material.iridescence_thickness_maximum_nm()",
        ],
    );
    require_contains(
        root,
        findings,
        "ASSETS-M8",
        "src/render/gpu/material_upload.rs",
        &[
            "from_iridescence_texture",
            "from_iridescence_thickness_texture",
        ],
    );
    require_contains(
        root,
        findings,
        "ASSETS-M8",
        "src/render/gpu/material_bindings.rs",
        &[
            "IRIDESCENCE_BINDINGS",
            "IRIDESCENCE_THICKNESS_BINDINGS",
            "MATERIAL_TEXTURE_BINDING_INDICES",
        ],
    );
    require_contains(
        root,
        findings,
        "ASSETS-M8",
        "src/render/gpu/materials.rs",
        &[
            "MaterialTextureUpload::from_iridescence_texture",
            "MaterialTextureUpload::from_iridescence_thickness_texture",
            "scena.material.iridescence",
            "scena.material.iridescence_thickness",
        ],
    );
    require_contains(
        root,
        findings,
        "ASSETS-M8",
        "src/render/gpu/material_batched.rs",
        &[
            "scena.material.batched_iridescence",
            "scena.material.batched_iridescence_thickness",
        ],
    );
    require_contains(
        root,
        findings,
        "ASSETS-M8",
        "src/render/gpu/output_shader.wgsl",
        &[
            "iridescence_factors: vec4<f32>",
            "var iridescence_texture: texture_2d_array<f32>",
            "var iridescence_thickness_texture: texture_2d_array<f32>",
            "material.iridescence_factors.x * iridescence_sample.r",
            "mix(material.iridescence_factors.z, material.iridescence_factors.w, clamp(iridescence_thickness_sample.g, 0.0, 1.0))",
            "iridescence_light_contribution",
        ],
    );
    require_contains(
        root,
        findings,
        "ASSETS-M8",
        "src/render/gpu/output_shader_texture_2d.wgsl",
        &[
            "iridescence_factors: vec4<f32>",
            "var iridescence_texture: texture_2d<f32>",
            "var iridescence_thickness_texture: texture_2d<f32>",
            "iridescence_light_contribution",
        ],
    );
    require_contains(
        root,
        findings,
        "ASSETS-M8",
        "src/render/gpu/output.rs",
        &["triangle_shader_applies_iridescence_lobe_in_native_and_webgl2_variants"],
    );
}
